var c;c||=typeof Module !== 'undefined' ? Module : {};var l=Object.assign({},c),m=(a,b)=>{throw b;},q="object"==typeof window,t="function"==typeof importScripts,u="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,x="",y,z,A;
if(u){var fs=require("fs"),B=require("path");x=t?B.dirname(x)+"/":__dirname+"/";y=(a,b)=>{a=C(a)?new URL(a):B.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};A=a=>{a=y(a,!0);a.buffer||(a=new Uint8Array(a));return a};z=(a,b,d,f=!0)=>{a=C(a)?new URL(a):B.normalize(a);fs.readFile(a,f?void 0:"utf8",(g,e)=>{g?d(g):b(f?e.buffer:e)})};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=c);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof D||a.context instanceof D))throw a;
});m=(a,b)=>{process.exitCode=a;throw b;};c.inspect=()=>"[Emscripten Module object]"}else if(q||t)t?x=self.location.href:"undefined"!=typeof document&&document.currentScript&&(x=document.currentScript.src),x=0!==x.indexOf("blob:")?x.substr(0,x.replace(/[?#].*/,"").lastIndexOf("/")+1):"",y=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(A=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
z=(a,b,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?b(f.response):d()};f.onerror=d;f.send(null)};var aa=c.print||console.log.bind(console),E=c.printErr||console.error.bind(console);Object.assign(c,l);l=null;c.quit&&(m=c.quit);var F;c.wasmBinary&&(F=c.wasmBinary);"object"!=typeof WebAssembly&&G("no native wasm support detected");var H,I=!1,J,K,L=[],M=[],ba=[],N=[];
function ca(){var a=c.preRun.shift();L.unshift(a)}var R=0,S=null,T=null;function G(a){c.onAbort?.(a);a="Aborted("+a+")";E(a);I=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var U=a=>a.startsWith("data:application/octet-stream;base64,"),C=a=>a.startsWith("file://"),V;V="index.wasm";if(!U(V)){var da=V;V=c.locateFile?c.locateFile(da,x):x+da}
function ea(a){if(a==V&&F)return new Uint8Array(F);if(A)return A(a);throw"both async and sync fetching of the wasm failed";}function ha(a){if(!F&&(q||t)){if("function"==typeof fetch&&!C(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>ea(a));if(z)return new Promise((b,d)=>{z(a,f=>b(new Uint8Array(f)),d)})}return Promise.resolve().then(()=>ea(a))}
function ia(a,b,d){return ha(a).then(f=>WebAssembly.instantiate(f,b)).then(f=>f).then(d,f=>{E(`failed to asynchronously prepare wasm: ${f}`);G(f)})}function ja(a,b){var d=V;F||"function"!=typeof WebAssembly.instantiateStreaming||U(d)||C(d)||u||"function"!=typeof fetch?ia(d,a,b):fetch(d,{credentials:"same-origin"}).then(f=>WebAssembly.instantiateStreaming(f,a).then(b,function(g){E(`wasm streaming compile failed: ${g}`);E("falling back to ArrayBuffer instantiation");return ia(d,a,b)}))}
function D(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var W=a=>{for(;0<a.length;)a.shift()(c)},ka=c.noExitRuntime||!0,X=[],la,ma=[null,[],[]],na="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,oa={b:(a,b,d)=>J.copyWithin(a,b,b+d),i:(a,b)=>{function d(f){var g=X[a];g||(a>=X.length&&(X.length=a+1),X[a]=g=la.get(a));g(f,b)&&requestAnimationFrame(d)}return requestAnimationFrame(d)},a:(a,b,d,f)=>{for(var g=0,e=0;e<d;e++){var p=K[b>>2],v=K[b+4>>2];b+=8;for(var O=0;O<v;O++){var h=J[p+O],P=ma[a];if(0===h||10===h){h=P;for(var n=0,r=n+NaN,w=n;h[w]&&
!(w>=r);)++w;if(16<w-n&&h.buffer&&na)h=na.decode(h.subarray(n,w));else{for(r="";n<w;){var k=h[n++];if(k&128){var Q=h[n++]&63;if(192==(k&224))r+=String.fromCharCode((k&31)<<6|Q);else{var fa=h[n++]&63;k=224==(k&240)?(k&15)<<12|Q<<6|fa:(k&7)<<18|Q<<12|fa<<6|h[n++]&63;65536>k?r+=String.fromCharCode(k):(k-=65536,r+=String.fromCharCode(55296|k>>10,56320|k&1023))}}else r+=String.fromCharCode(k)}h=r}(1===a?aa:E)(h);P.length=0}else P.push(h)}g+=v}K[f>>2]=g;return 0},g:function(){if(c._ntBlurred)c._nt_input_web_on_blur(),
c._ntBlurred=!1,c._ntKeyBuf.length=0,c._ntPtrBuf.length=0,c._ntWheelBuf.length=0;else{for(var a=c._ntKeyBuf,b=0;b<a.length;b+=2)c._nt_input_web_on_key(a[b],a[b+1]);a.length=0;a=c._ntPtrBuf;for(b=0;b<a.length;b+=7)0===a[b]?c._nt_input_web_on_pointer_down(a[b+1],a[b+2],a[b+3],a[b+4],a[b+5],a[b+6]):1===a[b]?c._nt_input_web_on_pointer_move(a[b+1],a[b+2],a[b+3],a[b+4],a[b+5],a[b+6]):c._nt_input_web_on_pointer_up(a[b+1]);a.length=0;a=c._ntWheelBuf;for(b=0;b<a.length;b+=2)c._nt_input_web_on_wheel(a[b],a[b+
1]);a.length=0}},h:function(){for(var a=c.canvas,b={},d=0;26>d;d++)b["Key"+"ABCDEFGHIJKLMNOPQRSTUVWXYZ"[d]]=d;for(d=0;10>d;d++)b["Digit"+d]=26+d;b.ArrowUp=36;b.ArrowDown=37;b.ArrowLeft=38;b.ArrowRight=39;b.Space=40;b.Enter=41;b.Escape=42;b.Tab=43;b.Backspace=44;b.ShiftLeft=45;b.ShiftRight=46;b.ControlLeft=47;b.ControlRight=48;b.AltLeft=49;b.AltRight=50;for(d=1;12>=d;d++)b["F"+d]=50+d;b.Delete=63;b.Insert=64;b.Home=65;b.End=66;b.PageUp=67;b.PageDown=68;var f={Space:1,Tab:1,ArrowUp:1,ArrowDown:1,ArrowLeft:1,
ArrowRight:1,F1:1,F2:1,F3:1,F4:1,F6:1,F7:1,F8:1,F9:1,F10:1},g=a.getBoundingClientRect();(new ResizeObserver(function(){g=a.getBoundingClientRect()})).observe(a);c._ntKeyBuf=[];c._ntPtrBuf=[];c._ntWheelBuf=[];c._ntBlurred=!1;a.addEventListener("keydown",function(e){if(!e.repeat){var p=b[e.code];void 0!==p&&c._ntKeyBuf.push(p,1);f[e.code]&&e.preventDefault()}});a.addEventListener("keyup",function(e){e=b[e.code];void 0!==e&&c._ntKeyBuf.push(e,0)});a.addEventListener("blur",function(){c._ntBlurred=!0});
a.addEventListener("pointerdown",function(e){a.focus();a.setPointerCapture(e.pointerId);c._ntPtrBuf.push(0,e.pointerId,e.clientX-g.left,e.clientY-g.top,e.pressure,"touch"===e.pointerType?1:"pen"===e.pointerType?2:0,e.buttons);e.preventDefault()});a.addEventListener("pointermove",function(e){c._ntPtrBuf.push(1,e.pointerId,e.clientX-g.left,e.clientY-g.top,e.pressure,"touch"===e.pointerType?1:"pen"===e.pointerType?2:0,e.buttons)});a.addEventListener("pointerup",function(e){"mouse"===e.pointerType?c._ntPtrBuf.push(1,
e.pointerId,e.clientX-g.left,e.clientY-g.top,e.pressure,0,e.buttons):c._ntPtrBuf.push(2,e.pointerId,0,0,0,0,0);e.preventDefault()});a.addEventListener("pointercancel",function(e){c._ntPtrBuf.push(2,e.pointerId,0,0,0,0,0);e.preventDefault()});a.addEventListener("pointerleave",function(e){"mouse"===e.pointerType&&c._ntPtrBuf.push(2,e.pointerId,0,0,0,0,0)});a.addEventListener("wheel",function(e){var p=e.deltaX,v=e.deltaY;1===e.deltaMode?(p*=16,v*=16):2===e.deltaMode&&(p*=window.innerWidth,v*=window.innerHeight);
c._ntWheelBuf.push(p,v);e.preventDefault()},{passive:!1});a.style.touchAction="none"},j:function(){var a=document.getElementById("spinner");a&&(a.style.display="none")},e:function(){return c.canvas.clientHeight},f:function(){return c.canvas.clientWidth},d:function(){return window.devicePixelRatio||1},c:function(a,b){c.canvas.width=a;c.canvas.height=b}},Y=function(){function a(d){Y=d.exports;H=Y.k;d=H.buffer;c.HEAP8=new Int8Array(d);c.HEAP16=new Int16Array(d);c.HEAPU8=J=new Uint8Array(d);c.HEAPU16=
new Uint16Array(d);c.HEAP32=new Int32Array(d);c.HEAPU32=K=new Uint32Array(d);c.HEAPF32=new Float32Array(d);c.HEAPF64=new Float64Array(d);la=Y.m;M.unshift(Y.l);R--;c.monitorRunDependencies?.(R);0==R&&(null!==S&&(clearInterval(S),S=null),T&&(d=T,T=null,d()));return Y}var b={a:oa};R++;c.monitorRunDependencies?.(R);if(c.instantiateWasm)try{return c.instantiateWasm(b,a)}catch(d){return E(`Module.instantiateWasm callback failed with error: ${d}`),!1}ja(b,function(d){a(d.instance)});return{}}(),pa=c._main=
(a,b)=>(pa=c._main=Y.n)(a,b);c._nt_input_web_on_key=(a,b)=>(c._nt_input_web_on_key=Y.o)(a,b);c._nt_input_web_on_pointer_down=(a,b,d,f,g,e)=>(c._nt_input_web_on_pointer_down=Y.p)(a,b,d,f,g,e);c._nt_input_web_on_pointer_move=(a,b,d,f,g,e)=>(c._nt_input_web_on_pointer_move=Y.q)(a,b,d,f,g,e);c._nt_input_web_on_pointer_up=a=>(c._nt_input_web_on_pointer_up=Y.r)(a);c._nt_input_web_on_wheel=(a,b)=>(c._nt_input_web_on_wheel=Y.s)(a,b);c._nt_input_web_on_blur=()=>(c._nt_input_web_on_blur=Y.t)();
c.___start_em_js=2088;c.___stop_em_js=6460;var Z;T=function qa(){Z||ra();Z||(T=qa)};
function ra(){function a(){if(!Z&&(Z=!0,c.calledRun=!0,!I)){W(M);W(ba);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(sa){var b=pa;try{var d=b(0,0);ka||(c.onExit?.(d),I=!0);m(d,new D(d))}catch(f){f instanceof D||"unwind"==f||m(1,f)}}if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;)b=c.postRun.shift(),N.unshift(b);W(N)}}if(!(0<R)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)ca();W(L);0<R||(c.setStatus?(c.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){c.setStatus("")},1);a()},1)):a())}}if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();var sa=!0;c.noInitialRun&&(sa=!1);ra();
