#ifndef NT_BASISU_ENCODER_H
#define NT_BASISU_ENCODER_H

#include "nt_basisu_codec.h"

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* One-time encoder initialization (call before first encode) */
void nt_basisu_encoder_init(void);

/* Caller frees data with nt_basisu_encode_free(). */
typedef struct {
    uint8_t *data;      /* Basis file data (caller frees via nt_basisu_encode_free) */
    uint32_t size;      /* size of Basis data in bytes */
    uint32_t mip_count; /* number of mip levels generated by encoder */
} nt_basisu_encode_result_t;

/* Borrows RGBA8 pixels and ETC1S/UASTC_LDR opts for the call.
 * Full mip chain; has_alpha checks alpha; NULL data on failure.
 * Thread-safe after init; basis_threads counts caller (min 1). */
nt_basisu_encode_result_t nt_basisu_encode(uint32_t basis_threads, const uint8_t *rgba_pixels, uint32_t width, uint32_t height, bool has_alpha, const nt_basisu_encode_opts_t *opts);

/* Free encoder output data */
void nt_basisu_encode_free(nt_basisu_encode_result_t *result);

#ifdef __cplusplus
}
#endif

#endif /* NT_BASISU_ENCODER_H */
