#ifndef NT_BASISU_ENCODER_H
#define NT_BASISU_ENCODER_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* One-time encoder initialization (call before first encode) */
void nt_basisu_encoder_init(void);

/* Encode result -- caller must free output_data via nt_basisu_encode_free() */
typedef struct {
    uint8_t *data;      /* Basis file data (caller frees via nt_basisu_encode_free) */
    uint32_t size;      /* size of Basis data in bytes */
    uint32_t mip_count; /* number of mip levels generated by encoder */
} nt_basisu_encode_result_t;

/* Encode RGBA pixels to Basis Universal format.
 * rgba_pixels: RGBA8 pixel data (width * height * 4 bytes)
 * width, height: image dimensions
 * has_alpha: true if alpha channel is meaningful (false = RGB-only optimization)
 * uastc: false = ETC1S mode, true = UASTC mode
 * quality: ETC1S: 1-255, UASTC: 0-4 (pack level)
 * rdo_quality: ETC1S rate-distortion optimization (0.0 = disabled), UASTC: ignored
 * gen_mipmaps: true = encoder generates full mip chain
 * Returns: result with data pointer and size. data=NULL on failure.
 */
nt_basisu_encode_result_t nt_basisu_encode(const uint8_t *rgba_pixels, uint32_t width, uint32_t height, bool has_alpha, bool uastc, uint32_t quality, float rdo_quality, bool gen_mipmaps);

/* Free encoder output data */
void nt_basisu_encode_free(nt_basisu_encode_result_t *result);

#ifdef __cplusplus
}
#endif

#endif /* NT_BASISU_ENCODER_H */
