var e;e||=typeof Module !== 'undefined' ? Module : {};var ba=Object.assign({},e),h=(a,b)=>{throw b;},ca="object"==typeof window,l="function"==typeof importScripts,da="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",r,t,u;
if(da){var fs=require("fs"),v=require("path");q=l?v.dirname(q)+"/":__dirname+"/";r=(a,b)=>{a=w(a)?new URL(a):v.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};u=a=>{a=r(a,!0);a.buffer||(a=new Uint8Array(a));return a};t=(a,b,c,d=!0)=>{a=w(a)?new URL(a):v.normalize(a);fs.readFile(a,d?void 0:"utf8",(g,f)=>{g?c(g):b(d?f.buffer:f)})};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof x||a.context instanceof x))throw a;
});h=(a,b)=>{process.exitCode=a;throw b;};e.inspect=()=>"[Emscripten Module object]"}else if(ca||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",r=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(u=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
t=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ea=e.print||console.log.bind(console),y=e.printErr||console.error.bind(console);Object.assign(e,ba);ba=null;e.quit&&(h=e.quit);var z;e.wasmBinary&&(z=e.wasmBinary);"object"!=typeof WebAssembly&&fa("no native wasm support detected");var A,B=!1,ha,C,ia,ja,D,E,F;
function ka(){var a=A.buffer;e.HEAP8=ha=new Int8Array(a);e.HEAP16=ia=new Int16Array(a);e.HEAPU8=C=new Uint8Array(a);e.HEAPU16=ja=new Uint16Array(a);e.HEAP32=D=new Int32Array(a);e.HEAPU32=E=new Uint32Array(a);e.HEAPF32=F=new Float32Array(a);e.HEAPF64=new Float64Array(a)}var la=[],ma=[],na=[],oa=[];function pa(){var a=e.preRun.shift();la.unshift(a)}var G=0,H=null,I=null;
function fa(a){e.onAbort?.(a);a="Aborted("+a+")";y(a);B=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var qa=a=>a.startsWith("data:application/octet-stream;base64,"),w=a=>a.startsWith("file://"),J;J="index.wasm";if(!qa(J)){var ra=J;J=e.locateFile?e.locateFile(ra,q):q+ra}function sa(a){if(a==J&&z)return new Uint8Array(z);if(u)return u(a);throw"both async and sync fetching of the wasm failed";}
function ta(a){if(!z&&(ca||l)){if("function"==typeof fetch&&!w(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>sa(a));if(t)return new Promise((b,c)=>{t(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>sa(a))}function ua(a,b,c){return ta(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{y(`failed to asynchronously prepare wasm: ${d}`);fa(d)})}
function va(a,b){var c=J;z||"function"!=typeof WebAssembly.instantiateStreaming||qa(c)||w(c)||da||"function"!=typeof fetch?ua(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(g){y(`wasm streaming compile failed: ${g}`);y("falling back to ArrayBuffer instantiation");return ua(c,a,b)}))}function x(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var K=a=>{for(;0<a.length;)a.shift()(e)},wa=e.noExitRuntime||!0,xa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,L=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&xa)return xa.decode(a.subarray(b,c));for(d="";b<c;){var g=a[b++];if(g&128){var f=a[b++]&63;if(192==(g&224))d+=String.fromCharCode((g&31)<<6|f);else{var k=a[b++]&63;g=224==(g&240)?(g&15)<<12|f<<6|k:(g&7)<<18|f<<12|k<<6|a[b++]&63;65536>g?d+=String.fromCharCode(g):(g-=65536,d+=String.fromCharCode(55296|
g>>10,56320|g&1023))}}else d+=String.fromCharCode(g)}return d},ya=1,M=[],N=[],O=[],P=[],za=[],Q=[];function R(a){Aa||=a}
var S=a=>{for(var b=ya++,c=a.length;c<b;c++)a[c]=null;return b},Ca=(a,b)=>{a.Fa||(a.Fa=a.getContext,a.getContext=function(d,g){g=a.Fa(d,g);return"webgl"==d==g instanceof WebGLRenderingContext?g:null});var c=a.getContext("webgl2",b);return c?Ba(c,b):0},Ba=(a,b)=>{var c=S(Q),d={handle:c,attributes:b,version:b.Ma,sa:a};a.canvas&&(a.canvas.Ia=d);Q[c]=d;("undefined"==typeof b.Ea||b.Ea)&&Da(d);return c},Da=a=>{a||=T;if(!a.La){a.La=!0;var b=a.sa;b.Ua=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");
b.Xa=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Da=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Da)b.Da=b.getExtension("EXT_disjoint_timer_query");b.Za=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},Aa,T,U=[],Ea,V=[],Fa={},Ga=["default","low-power","high-performance"],Ha=[0,"undefined"!=typeof document?document:0,"undefined"!=
typeof window?window:0],Ia=[null,[],[]],X=(a,b,c,d)=>{for(var g=0;g<a;g++){var f=W[c](),k=f&&S(d);f?(f.name=k,d[k]=f):R(1282);D[b+4*g>>2]=k}},Ja=(a,b,c)=>{var d=C;if(!(0<c))return 0;var g=b;c=b+c-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var m=a.charCodeAt(++f);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(b>=c)break;d[b++]=k}else{if(2047>=k){if(b+1>=c)break;d[b++]=192|k>>6}else{if(65535>=k){if(b+2>=c)break;d[b++]=224|k>>12}else{if(b+3>=c)break;d[b++]=240|k>>18;d[b++]=
128|k>>12&63}d[b++]=128|k>>6&63}d[b++]=128|k&63}}d[b]=0;return b-g},Ka=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),La=a=>{var b=W.Ja;if(b){var c=b.ta[a];"number"==typeof c&&(b.ta[a]=c=W.getUniformLocation(b,b.Ga[a]+(0<c?`[${c}]`:"")));return c}R(1282)},W,Ma={v:a=>!Q[a]||Q[a].sa.isContextLost(),u:(a,b,c)=>C.copyWithin(a,b,b+c),fa:(a,b)=>{function c(d){var g=U[a];g||(a>=U.length&&(U.length=a+1),U[a]=g=Ea.get(a));g(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},s:a=>{var b=C.length;a>>>=
0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var g=Math;d=Math.max(a,d);a:{g=(g.min.call(g,2147483648,d+(65536-d%65536)%65536)-A.buffer.byteLength+65535)/65536;try{A.grow(g);ka();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},y:(a,b)=>{b>>=2;b={alpha:!!D[b],depth:!!D[b+1],stencil:!!D[b+2],antialias:!!D[b+3],premultipliedAlpha:!!D[b+4],preserveDrawingBuffer:!!D[b+5],powerPreference:Ga[D[b+6]],failIfMajorPerformanceCaveat:!!D[b+7],Ma:D[b+8],
Ya:D[b+9],Ea:D[b+10],Ka:D[b+11],$a:D[b+12],ab:D[b+13]};a=2<a?a?L(C,a):"":a;a=Ha[a]||("undefined"!=typeof document?document.querySelector(a):void 0);return!a||b.Ka?0:Ca(a,b)},w:a=>{T==a&&(T=0);T===Q[a]&&(T=null);if("object"==typeof Fa)for(var b=Q[a].sa.canvas,c=0;c<V.length;++c)if(V[c].target==b){var d=c--,g=V[d];g.target.removeEventListener(g.Wa,g.Va,g.bb);V.splice(d,1)}Q[a]&&Q[a].sa.canvas&&(Q[a].sa.canvas.Ia=void 0);Q[a]=null},z:a=>{a>>=2;for(var b=0;14>b;++b)D[a+b]=0;D[a]=D[a+1]=D[a+3]=D[a+4]=
D[a+8]=D[a+10]=1},x:a=>{T=Q[a];e.Ta=W=T?.sa;return!a||W?0:-5},t:()=>52,q:function(){return 70},g:(a,b,c,d)=>{for(var g=0,f=0;f<c;f++){var k=E[b>>2],m=E[b+4>>2];b+=8;for(var p=0;p<m;p++){var n=C[k+p],aa=Ia[a];0===n||10===n?((1===a?ea:y)(L(aa,0)),aa.length=0):aa.push(n)}g+=m}E[d>>2]=g;return 0},A:function(a){W.activeTexture(a)},l:(a,b)=>{W.attachShader(N[a],P[b])},d:(a,b)=>{35051==a?W.Ca=b:35052==a&&(W.Aa=b);W.bindBuffer(a,M[b])},h:(a,b)=>{W.bindTexture(a,O[b])},f:a=>{W.bindVertexArray(za[a])},_:function(a,
b){W.blendFunc(a,b)},I:(a,b,c,d)=>{c&&b?W.bufferData(a,C,d,c,b):W.bufferData(a,b,d)},da:function(a){W.clear(a)},n:function(a,b,c,d){W.clearColor(a,b,c,d)},ea:function(a){W.clearDepth(a)},S:a=>{W.compileShader(P[a])},R:()=>{var a=S(N),b=W.createProgram();b.name=a;b.xa=b.va=b.wa=0;b.Ba=1;N[a]=b;return a},U:a=>{var b=S(P);P[b]=W.createShader(a);return b},$:function(a){W.cullFace(a)},H:(a,b)=>{for(var c=0;c<a;c++){var d=D[b+4*c>>2],g=M[d];g&&(W.deleteBuffer(g),g.name=0,M[d]=null,d==W.Ca&&(W.Ca=0),d==
W.Aa&&(W.Aa=0))}},k:a=>{if(a){var b=N[a];b?(W.deleteProgram(b),b.name=0,N[a]=null):R(1281)}},e:a=>{if(a){var b=P[a];b?(W.deleteShader(b),P[a]=null):R(1281)}},C:(a,b)=>{for(var c=0;c<a;c++){var d=D[b+4*c>>2],g=O[d];g&&(W.deleteTexture(g),g.name=0,O[d]=null)}},ba:function(a){W.depthFunc(a)},aa:a=>{W.depthMask(!!a)},b:function(a){W.disable(a)},V:(a,b,c,d)=>{W.drawElements(a,b,c,d)},c:function(a){W.enable(a)},j:a=>{W.enableVertexAttribArray(a)},K:(a,b)=>{X(a,b,"createBuffer",M)},F:(a,b)=>{X(a,b,"createTexture",
O)},N:function(a,b){X(a,b,"createVertexArray",za)},D:function(a){W.generateMipmap(a)},L:(a,b,c,d)=>{a=W.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ja(a,d,b):0;c&&(D[c>>2]=b)},O:(a,b,c)=>{if(c)if(a>=ya)R(1281);else if(a=N[a],35716==b)a=W.getProgramInfoLog(a),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1;else if(35719==b){if(!a.xa)for(b=0;b<W.getProgramParameter(a,35718);++b)a.xa=Math.max(a.xa,W.getActiveUniform(a,b).name.length+1);D[c>>2]=a.xa}else if(35722==b){if(!a.va)for(b=
0;b<W.getProgramParameter(a,35721);++b)a.va=Math.max(a.va,W.getActiveAttrib(a,b).name.length+1);D[c>>2]=a.va}else if(35381==b){if(!a.wa)for(b=0;b<W.getProgramParameter(a,35382);++b)a.wa=Math.max(a.wa,W.getActiveUniformBlockName(a,b).length+1);D[c>>2]=a.wa}else D[c>>2]=W.getProgramParameter(a,b);else R(1281)},i:(a,b,c,d)=>{a=W.getShaderInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ja(a,d,b):0;c&&(D[c>>2]=b)},m:(a,b)=>{b=b?L(C,b):"";if(a=N[a]){var c=a,d=c.ta,g=c.Ha,f;if(!d)for(c.ta=d={},c.Ga=
{},f=0;f<W.getProgramParameter(c,35718);++f){var k=W.getActiveUniform(c,f);var m=k.name;k=k.size;var p=Ka(m);p=0<p?m.slice(0,p):m;var n=c.Ba;c.Ba+=k;g[p]=[k,n];for(m=0;m<k;++m)d[n]=m,c.Ga[n++]=p}c=a.ta;d=0;g=b;f=Ka(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,g=b.slice(0,f));if((g=a.Ha[g])&&d<g[0]&&(d+=g[1],c[d]=c[d]||W.getUniformLocation(a,b)))return d}else R(1281);return-1},P:a=>{a=N[a];W.linkProgram(a);a.ta=0;a.Ha={}},Y:function(a,b){W.polygonOffset(a,b)},T:(a,b,c,d)=>{for(var g="",f=0;f<b;++f){var k=
d?D[d+4*f>>2]:-1,m=D[c+4*f>>2];k=m?L(C,m,0>k?void 0:k):"";g+=k}W.shaderSource(P[a],g)},E:(a,b,c,d,g,f,k,m,p)=>{if(W.Aa)W.texImage2D(a,b,c,d,g,f,k,m,p);else if(p){var n=m-5120;n=0==n?ha:1==n?C:2==n?ia:4==n?D:6==n?F:5==n||28922==n||28520==n||30779==n||30782==n?E:ja;W.texImage2D(a,b,c,d,g,f,k,m,n,p>>31-Math.clz32(n.BYTES_PER_ELEMENT))}else W.texImage2D(a,b,c,d,g,f,k,m,null)},a:function(a,b,c){W.texParameteri(a,b,c)},W:(a,b)=>{W.uniform1i(La(a),b)},X:(a,b,c,d)=>{b&&W.uniformMatrix4fv(La(a),!!c,F,d>>2,
16*b)},ca:a=>{a=N[a];W.useProgram(a);W.Ja=a},M:(a,b)=>{W.vertexAttribDivisor(a,b)},G:(a,b,c,d,g,f)=>{W.vertexAttribPointer(a,b,c,!!d,g,f)},o:function(a,b,c,d){W.viewport(a,b,c,d)},Q:function(){if(e.ya)e.Na(),e.ya=!1,e.ua.length=0,e.ra.length=0,e.za.length=0;else{for(var a=e.ua,b=0;b<a.length;b+=2)e.Oa(a[b],a[b+1]);a.length=0;a=e.ra;for(b=0;b<a.length;b+=7)0===a[b]?e.Pa(a[b+1],a[b+2],a[b+3],a[b+4],a[b+5],a[b+6]):1===a[b]?e.Qa(a[b+1],a[b+2],a[b+3],a[b+4],a[b+5],a[b+6]):e.Ra(a[b+1]);a.length=0;a=e.za;
for(b=0;b<a.length;b+=2)e.Sa(a[b],a[b+1]);a.length=0}},Z:function(){for(var a=e.canvas,b={},c=0;26>c;c++)b["Key"+"ABCDEFGHIJKLMNOPQRSTUVWXYZ"[c]]=c;for(c=0;10>c;c++)b["Digit"+c]=26+c;b.ArrowUp=36;b.ArrowDown=37;b.ArrowLeft=38;b.ArrowRight=39;b.Space=40;b.Enter=41;b.Escape=42;b.Tab=43;b.Backspace=44;b.ShiftLeft=45;b.ShiftRight=46;b.ControlLeft=47;b.ControlRight=48;b.AltLeft=49;b.AltRight=50;for(c=1;12>=c;c++)b["F"+c]=50+c;b.Delete=63;b.Insert=64;b.Home=65;b.End=66;b.PageUp=67;b.PageDown=68;var d={Space:1,
Tab:1,ArrowUp:1,ArrowDown:1,ArrowLeft:1,ArrowRight:1,F1:1,F2:1,F3:1,F4:1,F6:1,F7:1,F8:1,F9:1,F10:1},g=a.getBoundingClientRect();(new ResizeObserver(function(){g=a.getBoundingClientRect()})).observe(a);e.ua=[];e.ra=[];e.za=[];e.ya=!1;a.addEventListener("keydown",function(f){if(!f.repeat){var k=b[f.code];void 0!==k&&e.ua.push(k,1);d[f.code]&&f.preventDefault()}});a.addEventListener("keyup",function(f){f=b[f.code];void 0!==f&&e.ua.push(f,0)});a.addEventListener("blur",function(){e.ya=!0});a.addEventListener("pointerdown",
function(f){a.focus();a.setPointerCapture(f.pointerId);e.ra.push(0,f.pointerId,f.clientX-g.left,f.clientY-g.top,f.pressure,"touch"===f.pointerType?1:"pen"===f.pointerType?2:0,f.buttons);f.preventDefault()});a.addEventListener("pointermove",function(f){e.ra.push(1,f.pointerId,f.clientX-g.left,f.clientY-g.top,f.pressure,"touch"===f.pointerType?1:"pen"===f.pointerType?2:0,f.buttons)});a.addEventListener("pointerup",function(f){"mouse"===f.pointerType?e.ra.push(1,f.pointerId,f.clientX-g.left,f.clientY-
g.top,f.pressure,0,f.buttons):e.ra.push(2,f.pointerId,0,0,0,0,0);f.preventDefault()});a.addEventListener("pointercancel",function(f){e.ra.push(2,f.pointerId,0,0,0,0,0);f.preventDefault()});a.addEventListener("pointerleave",function(f){"mouse"===f.pointerType&&e.ra.push(2,f.pointerId,0,0,0,0,0)});a.addEventListener("wheel",function(f){var k=f.deltaX,m=f.deltaY;1===f.deltaMode?(k*=16,m*=16):2===f.deltaMode&&(k*=window.innerWidth,m*=window.innerHeight);e.za.push(k,m);f.preventDefault()},{passive:!1});
a.style.touchAction="none"},ga:function(){var a=document.getElementById("spinner");a&&(a.style.display="none")},B:function(){return e.canvas.clientHeight},J:function(){return e.canvas.clientWidth},r:function(){return window.devicePixelRatio||1},p:function(a,b){e.canvas.width=a;e.canvas.height=b}},Y=function(){function a(c){Y=c.exports;A=Y.ha;ka();Ea=Y.ja;ma.unshift(Y.ia);G--;e.monitorRunDependencies?.(G);0==G&&(null!==H&&(clearInterval(H),H=null),I&&(c=I,I=null,c()));return Y}var b={a:Ma};G++;e.monitorRunDependencies?.(G);
if(e.instantiateWasm)try{return e.instantiateWasm(b,a)}catch(c){return y(`Module.instantiateWasm callback failed with error: ${c}`),!1}va(b,function(c){a(c.instance)});return{}}(),Na=e._main=(a,b)=>(Na=e._main=Y.ka)(a,b);e._nt_input_web_on_key=(a,b)=>(e._nt_input_web_on_key=Y.la)(a,b);e._nt_input_web_on_pointer_down=(a,b,c,d,g,f)=>(e._nt_input_web_on_pointer_down=Y.ma)(a,b,c,d,g,f);e._nt_input_web_on_pointer_move=(a,b,c,d,g,f)=>(e._nt_input_web_on_pointer_move=Y.na)(a,b,c,d,g,f);
e._nt_input_web_on_pointer_up=a=>(e._nt_input_web_on_pointer_up=Y.oa)(a);e._nt_input_web_on_wheel=(a,b)=>(e._nt_input_web_on_wheel=Y.pa)(a,b);e._nt_input_web_on_blur=()=>(e._nt_input_web_on_blur=Y.qa)();e.___start_em_js=4172;e.___stop_em_js=8445;var Z;I=function Oa(){Z||Pa();Z||(I=Oa)};
function Pa(){function a(){if(!Z&&(Z=!0,e.calledRun=!0,!B)){K(ma);K(na);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Qa){var b=Na;try{var c=b(0,0);wa||(e.onExit?.(c),B=!0);h(c,new x(c))}catch(d){d instanceof x||"unwind"==d||h(1,d)}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)b=e.postRun.shift(),oa.unshift(b);K(oa)}}if(!(0<G)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)pa();K(la);0<G||(e.setStatus?(e.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Qa=!0;e.noInitialRun&&(Qa=!1);Pa();
