var g;g||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},g),k=(a,b)=>{throw b;},ba="object"==typeof window,p="function"==typeof importScripts,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,x="",da,y,z;
if(ca){var fs=require("fs"),ea=require("path");x=p?ea.dirname(x)+"/":__dirname+"/";da=(a,b)=>{a=C(a)?new URL(a):ea.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};z=a=>{a=da(a,!0);a.buffer||(a=new Uint8Array(a));return a};y=(a,b,c,d=!0)=>{a=C(a)?new URL(a):ea.normalize(a);fs.readFile(a,d?void 0:"utf8",(f,e)=>{f?c(f):b(d?e.buffer:e)})};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof D||a.context instanceof
D))throw a;});k=(a,b)=>{process.exitCode=a;throw b;};g.inspect=()=>"[Emscripten Module object]"}else if(ba||p)p?x=self.location.href:"undefined"!=typeof document&&document.currentScript&&(x=document.currentScript.src),x=0!==x.indexOf("blob:")?x.substr(0,x.replace(/[?#].*/,"").lastIndexOf("/")+1):"",da=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},p&&(z=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
y=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var fa=g.print||console.log.bind(console),E=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.quit&&(k=g.quit);var G;g.wasmBinary&&(G=g.wasmBinary);"object"!=typeof WebAssembly&&ha("no native wasm support detected");var H,ia=!1,I,J,ja,ka,K,L,la,ma;
function oa(){var a=H.buffer;g.HEAP8=I=new Int8Array(a);g.HEAP16=ja=new Int16Array(a);g.HEAPU8=J=new Uint8Array(a);g.HEAPU16=ka=new Uint16Array(a);g.HEAP32=K=new Int32Array(a);g.HEAPU32=L=new Uint32Array(a);g.HEAPF32=la=new Float32Array(a);g.HEAPF64=ma=new Float64Array(a)}var pa=[],qa=[],ra=[],sa=[];function ta(){var a=g.preRun.shift();pa.unshift(a)}var M=0,ua=null,N=null;
function ha(a){g.onAbort?.(a);a="Aborted("+a+")";E(a);ia=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va=a=>a.startsWith("data:application/octet-stream;base64,"),C=a=>a.startsWith("file://"),O;O="index.wasm";if(!va(O)){var wa=O;O=g.locateFile?g.locateFile(wa,x):x+wa}function xa(a){if(a==O&&G)return new Uint8Array(G);if(z)return z(a);throw"both async and sync fetching of the wasm failed";}
function ya(a){if(!G&&(ba||p)){if("function"==typeof fetch&&!C(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>xa(a));if(y)return new Promise((b,c)=>{y(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>xa(a))}function za(a,b,c){return ya(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{E(`failed to asynchronously prepare wasm: ${d}`);ha(d)})}
function Aa(a,b){var c=O;G||"function"!=typeof WebAssembly.instantiateStreaming||va(c)||C(c)||ca||"function"!=typeof fetch?za(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(f){E(`wasm streaming compile failed: ${f}`);E("falling back to ArrayBuffer instantiation");return za(c,a,b)}))}function D(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var P=a=>{for(;0<a.length;)a.shift()(g)},Ba=g.noExitRuntime||!0,Ca="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,Q=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ca)return Ca.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var e=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|e);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|e<<6|h:(f&7)<<18|e<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|
f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d},Da=1,R=[],S=[],Ea=[],T=[],Fa=[],U=[];function V(a){Ga||=a}
var Ha=a=>{for(var b=Da++,c=a.length;c<b;c++)a[c]=null;return b},Ja=(a,b)=>{a.Ma||(a.Ma=a.getContext,a.getContext=function(d,f){f=a.Ma(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl2",b);return c?Ia(c,b):0},Ia=(a,b)=>{var c=Ha(U),d={handle:c,attributes:b,version:b.Sa,za:a};a.canvas&&(a.canvas.Na=d);U[c]=d;("undefined"==typeof b.Ja||b.Ja)&&Ka(d);return c},Ka=a=>{a||=W;if(!a.Ra){a.Ra=!0;var b=a.za;b.Ua=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");
b.Xa=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Ia=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Ia)b.Ia=b.getExtension("EXT_disjoint_timer_query");b.Za=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},Ga,W,La=(a,b)=>{if(0>=a)return a;var c=32>=b?Math.abs(1<<b-1):Math.pow(2,b-1);a>=c&&(32>=b||a>c)&&(a=-2*c+a);return a},Ma=(a,b)=>
0<=a?a:32>=b?2*Math.abs(1<<b-1)+a:Math.pow(2,b)+a,Na=a=>{for(var b=a;J[b];)++b;return b-a},Oa=(a,b,c,d)=>{if(!(0<d))return 0;var f=c;d=c+d-1;for(var e=0;e<a.length;++e){var h=a.charCodeAt(e);if(55296<=h&&57343>=h){var l=a.charCodeAt(++e);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=
0;return c-f};function Pa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}b=Array(b+1);a=Oa(a,b,0,b.length);b.length=a;return b}
var Qa=(a,b)=>{function c(B){var na=d;("double"===B||"i64"===B)&&na&7&&(na+=4);d=na;"double"===B?(B=ma[d>>3],d+=8):"i64"==B?(B=[K[d>>2],K[d+4>>2]],d+=8):(B=K[d>>2],d+=4);return B}for(var d=b,f=[],e,h;;){var l=a;e=I[a>>0];if(0===e)break;h=I[a+1>>0];if(37==e){var u=!1,n=b=!1,q=!1,r=!1;a:for(;;){switch(h){case 43:u=!0;break;case 45:b=!0;break;case 35:n=!0;break;case 48:if(q)break a;else{q=!0;break}case 32:r=!0;break;default:break a}a++;h=I[a+1>>0]}var w=0;if(42==h)w=c("i32"),a++,h=I[a+1>>0];else for(;48<=
h&&57>=h;)w=10*w+(h-48),a++,h=I[a+1>>0];var A=!1,v=-1;if(46==h){v=0;A=!0;a++;h=I[a+1>>0];if(42==h)v=c("i32"),a++;else for(;;){h=I[a+1>>0];if(48>h||57<h)break;v=10*v+(h-48);a++}h=I[a+1>>0]}0>v&&(v=6,A=!1);switch(String.fromCharCode(h)){case "h":h=I[a+2>>0];if(104==h){a++;var t=1}else t=2;break;case "l":h=I[a+2>>0];108==h?(a++,t=8):t=4;break;case "L":case "q":case "j":t=8;break;case "z":case "t":case "I":t=4;break;default:t=null}t&&a++;h=I[a+1>>0];switch(String.fromCharCode(h)){case "d":case "i":case "u":case "o":case "x":case "X":case "p":l=
100==h||105==h;t=t||4;e=c("i"+8*t);8==t&&(e=117==h?(e[0]>>>0)+4294967296*(e[1]>>>0):(e[0]>>>0)+4294967296*e[1]);4>=t&&(e=(l?La:Ma)(e&Math.pow(256,t)-1,8*t));var F=Math.abs(e);l="";if(100==h||105==h)var m=La(e,8*t).toString(10);else if(117==h)m=Ma(e,8*t).toString(10),e=Math.abs(e);else if(111==h)m=(n?"0":"")+F.toString(8);else if(120==h||88==h){l=n&&0!=e?"0x":"";if(0>e){e=-e;m=(F-1).toString(16);F=[];for(n=0;n<m.length;n++)F.push((15-parseInt(m[n],16)).toString(16));for(m=F.join("");m.length<2*t;)m=
"f"+m}else m=F.toString(16);88==h&&(l=l.toUpperCase(),m=m.toUpperCase())}else 112==h&&(0===F?m="(nil)":(l="0x",m=F.toString(16)));if(A)for(;m.length<v;)m="0"+m;0<=e&&(u?l="+"+l:r&&(l=" "+l));"-"==m.charAt(0)&&(l="-"+l,m=m.substr(1));for(;l.length+m.length<w;)b?m+=" ":q?m="0"+m:l=" "+l;m=l+m;m.split("").forEach(function(B){f.push(B.charCodeAt(0))});break;case "f":case "F":case "e":case "E":case "g":case "G":e=c("double");if(isNaN(e))m="nan",q=!1;else if(isFinite(e)){A=!1;t=Math.min(v,20);if(103==h||
71==h)A=!0,v=v||1,t=parseInt(e.toExponential(t).split("e")[1],10),v>t&&-4<=t?(h=(103==h?"f":"F").charCodeAt(0),v-=t+1):(h=(103==h?"e":"E").charCodeAt(0),v--),t=Math.min(v,20);if(101==h||69==h)m=e.toExponential(t),/[eE][-+]\d$/.test(m)&&(m=m.slice(0,-1)+"0"+m.slice(-1));else if(102==h||70==h)m=e.toFixed(t),0===e&&(0>e||0===e&&-Infinity===1/e)&&(m="-"+m);l=m.split("e");if(A&&!n)for(;1<l[0].length&&l[0].includes(".")&&("0"==l[0].slice(-1)||"."==l[0].slice(-1));)l[0]=l[0].slice(0,-1);else for(n&&-1==
m.indexOf(".")&&(l[0]+=".");v>t++;)l[0]+="0";m=l[0]+(1<l.length?"e"+l[1]:"");69==h&&(m=m.toUpperCase());0<=e&&(u?m="+"+m:r&&(m=" "+m))}else m=(0>e?"-":"")+"inf",q=!1;for(;m.length<w;)m=b?m+" ":!q||"-"!=m[0]&&"+"!=m[0]?(q?"0":" ")+m:m[0]+"0"+m.slice(1);97>h&&(m=m.toUpperCase());m.split("").forEach(function(B){f.push(B.charCodeAt(0))});break;case "s":q=(u=c("i8*"))?Na(u):6;A&&(q=Math.min(q,v));if(!b)for(;q<w--;)f.push(32);if(u)for(n=0;n<q;n++)f.push(J[u++>>0]);else f=f.concat(Pa("(null)".substr(0,q)));
if(b)for(;q<w--;)f.push(32);break;case "c":for(b&&f.push(c("i8"));0<--w;)f.push(32);b||f.push(c("i8"));break;case "n":b=c("i32*");K[b>>2]=f.length;break;case "%":f.push(e);break;default:for(n=l;n<a+2;n++)f.push(I[n>>0])}a+=2}else f.push(e),a+=1}return f},X=()=>{var a='Source map information is not available, emscripten_log with EM_LOG_C_STACK will be ignored. Build with "--pre-js $EMSCRIPTEN/src/emscripten-source-map.min.js" linker flag to add source map loading to code.';X.Fa||(X.Fa={});X.Fa[a]||
(X.Fa[a]=1,ca&&(a="warning: "+a),E(a))},Ra=[],Sa,Ta=[],Ua={},Va=["default","low-power","high-performance"],Wa=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],Xa=[null,[],[]],Ya=(a,b,c,d)=>{for(var f=0;f<a;f++){var e=Y[c](),h=e&&Ha(d);e?(e.name=h,d[h]=e):V(1282);K[b+4*f>>2]=h}},Za=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),$a=a=>{var b=Y.Pa;if(b){var c=b.Aa[a];"number"==typeof c&&(b.Aa[a]=c=Y.getUniformLocation(b,b.Ka[a]+(0<c?`[${c}]`:"")));return c}V(1282)},Y,ab={r:()=>
performance.now(),z:a=>!U[a]||U[a].za.isContextLost(),h:(a,b,c)=>{b=Qa(b,c);c=Q(b,0);if(a&24){b=c=c.replace(/\s+$/,"");c=0<c.length?"\n":"";var d=a;a:{var f=Error();if(!f.stack){try{throw Error();}catch(F){f=F}if(!f.stack){f="(no stack trace available)";break a}}f=f.stack.toString()}f=f.slice(f.indexOf("\n",Math.max(f.lastIndexOf("_emscripten_log"),f.lastIndexOf("_emscripten_get_callstack")))+1);d&8&&"undefined"==typeof emscripten_source_map&&(X(),d=d^8|16);var e=f.split("\n");f="";var h=RegExp("\\s*(.*?)@(.*?):([0-9]+):([0-9]+)"),
l=RegExp("\\s*(.*?)@(.*):(.*)(:(.*))?"),u=RegExp("\\s*at (.*?) \\((.*):(.*):(.*)\\)"),n;for(n in e){var q=e[n],r;if((r=u.exec(q))&&5==r.length){q=r[1];var w=r[2];var A=r[3];r=r[4]}else if((r=h.exec(q))||(r=l.exec(q)),r&&4<=r.length)q=r[1],w=r[2],A=r[3],r=r[4]|0;else{f+=q+"\n";continue}var v=!1;if(d&8){var t=emscripten_source_map.$a({line:A,Oa:r});if(v=t?.source)d&64&&(t.source=t.source.substring(t.source.replace(/\\/g,"/").lastIndexOf("/")+1)),f+=`    at ${q} (${t.source}:${t.line}:${t.Oa})\n`}if(d&
16||!v)d&64&&(w=w.substring(w.replace(/\\/g,"/").lastIndexOf("/")+1)),f+=(v?`     = ${q}`:`    at ${q}`)+` (${w}:${A}:${r})\n`}f=f.replace(/\s+$/,"");c=b+(c+f)}a&1?a&4?console.error(c):a&2?console.warn(c):a&512?console.info(c):a&256?console.debug(c):console.log(c):a&6?E(c):fa(c)},w:(a,b,c)=>J.copyWithin(a,b,b+c),ja:(a,b)=>{function c(d){var f=Ra[a];f||(a>=Ra.length&&(Ra.length=a+1),Ra[a]=f=Sa.get(a));f(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},u:a=>{var b=J.length;a>>>=0;if(2147483648<
a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var f=Math;d=Math.max(a,d);a:{f=(f.min.call(f,2147483648,d+(65536-d%65536)%65536)-H.buffer.byteLength+65535)/65536;try{H.grow(f);oa();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},C:(a,b)=>{b>>=2;b={alpha:!!K[b],depth:!!K[b+1],stencil:!!K[b+2],antialias:!!K[b+3],premultipliedAlpha:!!K[b+4],preserveDrawingBuffer:!!K[b+5],powerPreference:Va[K[b+6]],failIfMajorPerformanceCaveat:!!K[b+7],Sa:K[b+8],Ya:K[b+9],Ja:K[b+
10],Qa:K[b+11],ab:K[b+12],bb:K[b+13]};a=2<a?a?Q(J,a):"":a;a=Wa[a]||("undefined"!=typeof document?document.querySelector(a):void 0);return!a||b.Qa?0:Ja(a,b)},A:a=>{W==a&&(W=0);W===U[a]&&(W=null);if("object"==typeof Ua)for(var b=U[a].za.canvas,c=0;c<Ta.length;++c)if(Ta[c].target==b){var d=c--,f=Ta[d];f.target.removeEventListener(f.Wa,f.Va,f.cb);Ta.splice(d,1)}U[a]&&U[a].za.canvas&&(U[a].za.canvas.Na=void 0);U[a]=null},D:a=>{a>>=2;for(var b=0;14>b;++b)K[a+b]=0;K[a]=K[a+1]=K[a+3]=K[a+4]=K[a+8]=K[a+10]=
1},B:a=>{W=U[a];g.Ta=Y=W?.za;return!a||Y?0:-5},v:()=>52,t:function(){return 70},f:(a,b,c,d)=>{for(var f=0,e=0;e<c;e++){var h=L[b>>2],l=L[b+4>>2];b+=8;for(var u=0;u<l;u++){var n=J[h+u],q=Xa[a];0===n||10===n?((1===a?fa:E)(Q(q,0)),q.length=0):q.push(n)}f+=l}L[d>>2]=f;return 0},E:function(a){Y.activeTexture(a)},o:(a,b)=>{Y.attachShader(S[a],T[b])},d:(a,b)=>{35051==a?Y.Ha=b:35052==a&&(Y.Ea=b);Y.bindBuffer(a,R[b])},j:(a,b)=>{Y.bindTexture(a,Ea[b])},e:a=>{Y.bindVertexArray(Fa[a])},aa:function(a,b){Y.blendFunc(a,
b)},K:(a,b,c,d)=>{c&&b?Y.bufferData(a,J,d,c,b):Y.bufferData(a,b,d)},ga:function(a){Y.clear(a)},ia:function(a,b,c,d){Y.clearColor(a,b,c,d)},ha:function(a){Y.clearDepth(a)},V:a=>{Y.compileShader(T[a])},S:()=>{var a=Ha(S),b=Y.createProgram();b.name=a;b.Da=b.Ba=b.Ca=0;b.Ga=1;S[a]=b;return a},X:a=>{var b=Ha(T);T[b]=Y.createShader(a);return b},ca:function(a){Y.cullFace(a)},k:(a,b)=>{for(var c=0;c<a;c++){var d=K[b+4*c>>2],f=R[d];f&&(Y.deleteBuffer(f),f.name=0,R[d]=null,d==Y.Ha&&(Y.Ha=0),d==Y.Ea&&(Y.Ea=0))}},
n:a=>{if(a){var b=S[a];b?(Y.deleteProgram(b),b.name=0,S[a]=null):V(1281)}},U:a=>{if(a){var b=T[a];b?(Y.deleteShader(b),T[a]=null):V(1281)}},i:(a,b)=>{for(var c=0;c<a;c++){var d=K[b+4*c>>2],f=Ea[d];f&&(Y.deleteTexture(f),f.name=0,Ea[d]=null)}},ea:function(a){Y.depthFunc(a)},da:a=>{Y.depthMask(!!a)},b:function(a){Y.disable(a)},Y:(a,b,c,d)=>{Y.drawElements(a,b,c,d)},c:function(a){Y.enable(a)},m:a=>{Y.enableVertexAttribArray(a)},L:(a,b)=>{Ya(a,b,"createBuffer",R)},I:(a,b)=>{Ya(a,b,"createTexture",Ea)},
P:function(a,b){Ya(a,b,"createVertexArray",Fa)},G:function(a){Y.generateMipmap(a)},N:(a,b,c,d)=>{a=Y.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?Oa(a,J,d,b):0;c&&(K[c>>2]=b)},Q:(a,b,c)=>{if(c)if(a>=Da)V(1281);else if(a=S[a],35716==b)a=Y.getProgramInfoLog(a),null===a&&(a="(unknown error)"),K[c>>2]=a.length+1;else if(35719==b){if(!a.Da)for(b=0;b<Y.getProgramParameter(a,35718);++b)a.Da=Math.max(a.Da,Y.getActiveUniform(a,b).name.length+1);K[c>>2]=a.Da}else if(35722==b){if(!a.Ba)for(b=
0;b<Y.getProgramParameter(a,35721);++b)a.Ba=Math.max(a.Ba,Y.getActiveAttrib(a,b).name.length+1);K[c>>2]=a.Ba}else if(35381==b){if(!a.Ca)for(b=0;b<Y.getProgramParameter(a,35382);++b)a.Ca=Math.max(a.Ca,Y.getActiveUniformBlockName(a,b).length+1);K[c>>2]=a.Ca}else K[c>>2]=Y.getProgramParameter(a,b);else V(1281)},l:(a,b,c,d)=>{a=Y.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?Oa(a,J,d,b):0;c&&(K[c>>2]=b)},p:(a,b)=>{b=b?Q(J,b):"";if(a=S[a]){var c=a,d=c.Aa,f=c.La,e;if(!d)for(c.Aa=d={},
c.Ka={},e=0;e<Y.getProgramParameter(c,35718);++e){var h=Y.getActiveUniform(c,e);var l=h.name;h=h.size;var u=Za(l);u=0<u?l.slice(0,u):l;var n=c.Ga;c.Ga+=h;f[u]=[h,n];for(l=0;l<h;++l)d[n]=l,c.Ka[n++]=u}c=a.Aa;d=0;f=b;e=Za(b);0<e&&(d=parseInt(b.slice(e+1))>>>0,f=b.slice(0,e));if((f=a.La[f])&&d<f[0]&&(d+=f[1],c[d]=c[d]||Y.getUniformLocation(a,b)))return d}else V(1281);return-1},R:a=>{a=S[a];Y.linkProgram(a);a.Aa=0;a.La={}},$:function(a,b){Y.polygonOffset(a,b)},W:(a,b,c,d)=>{for(var f="",e=0;e<b;++e){var h=
d?K[d+4*e>>2]:-1,l=K[c+4*e>>2];h=l?Q(J,l,0>h?void 0:h):"";f+=h}Y.shaderSource(T[a],f)},H:(a,b,c,d,f,e,h,l,u)=>{if(Y.Ea)Y.texImage2D(a,b,c,d,f,e,h,l,u);else if(u){var n=l-5120;n=0==n?I:1==n?J:2==n?ja:4==n?K:6==n?la:5==n||28922==n||28520==n||30779==n||30782==n?L:ka;Y.texImage2D(a,b,c,d,f,e,h,l,n,u>>31-Math.clz32(n.BYTES_PER_ELEMENT))}else Y.texImage2D(a,b,c,d,f,e,h,l,null)},a:function(a,b,c){Y.texParameteri(a,b,c)},Z:(a,b)=>{Y.uniform1i($a(a),b)},_:(a,b,c,d)=>{b&&Y.uniformMatrix4fv($a(a),!!c,la,d>>
2,16*b)},fa:a=>{a=S[a];Y.useProgram(a);Y.Pa=a},O:(a,b)=>{Y.vertexAttribDivisor(a,b)},J:(a,b,c,d,f,e)=>{Y.vertexAttribPointer(a,b,c,!!d,f,e)},q:function(a,b,c,d){Y.viewport(a,b,c,d)},y:function(a){g._nt_http_controllers&&g._nt_http_controllers[a]&&(g._nt_http_controllers[a].abort(),delete g._nt_http_controllers[a])},g:function(a,b,c){c=c?Q(J,c):"";g._nt_http_controllers||(g._nt_http_controllers={});var d=new AbortController;g._nt_http_controllers[a]=d;console.log("[nt_http] fetch start slot="+a+" gen="+
b+" url="+c);fetch(c,{signal:d.signal}).then(function(f){console.log("[nt_http] response slot="+a+" status="+f.status+" ok="+f.ok+" hasBody="+!!f.body);if(f.ok)if(f.body&&"function"===typeof f.body.getReader){var e=f.headers.get("Content-Length"),h=e?parseInt(e,10):0,l=0,u=[],n=f.body.getReader();function q(){n.read().then(function(r){if(r.done){r=l;console.log("[nt_http] stream done slot="+a+" size="+r);for(var w=g._malloc(r),A=0,v=0;v<u.length;v++)g.HEAPU8.set(u[v],w+A),A+=u[v].length;g._nt_http_web_on_complete(a,
b,w,r,1)}else r=r.value,u.push(r),l+=r.length,g._nt_http_web_on_progress(a,b,l,h),q()}).catch(function(r){console.error("[nt_http] stream error slot="+a,r);g._nt_http_web_on_complete(a,b,0,0,0)})}q()}else f.arrayBuffer().then(function(q){q=new Uint8Array(q);var r=g._malloc(q.length);g.HEAPU8.set(q,r);g._nt_http_web_on_complete(a,b,r,q.length,1)}).catch(function(){g._nt_http_web_on_complete(a,b,0,0,0)});else g._nt_http_web_on_complete(a,b,0,0,0)}).catch(function(f){f&&"AbortError"===f.name||g._nt_http_web_on_complete(a,
b,0,0,0)})},T:function(){if(g._ntBlurred)g._nt_input_web_on_blur(),g._ntBlurred=!1,g._ntKeyBuf.length=0,g._ntPtrBuf.length=0,g._ntWheelBuf.length=0;else{for(var a=g._ntKeyBuf,b=0;b<a.length;b+=2)g._nt_input_web_on_key(a[b],a[b+1]);a.length=0;a=g._ntPtrBuf;for(b=0;b<a.length;b+=7)0===a[b]?g._nt_input_web_on_pointer_down(a[b+1],a[b+2],a[b+3],a[b+4],a[b+5],a[b+6]):1===a[b]?g._nt_input_web_on_pointer_move(a[b+1],a[b+2],a[b+3],a[b+4],a[b+5],a[b+6]):g._nt_input_web_on_pointer_up(a[b+1]);a.length=0;a=g._ntWheelBuf;
for(b=0;b<a.length;b+=2)g._nt_input_web_on_wheel(a[b],a[b+1]);a.length=0}},ba:function(){for(var a=g.canvas,b={},c=0;26>c;c++)b["Key"+"ABCDEFGHIJKLMNOPQRSTUVWXYZ"[c]]=c;for(c=0;10>c;c++)b["Digit"+c]=26+c;b.ArrowUp=36;b.ArrowDown=37;b.ArrowLeft=38;b.ArrowRight=39;b.Space=40;b.Enter=41;b.Escape=42;b.Tab=43;b.Backspace=44;b.ShiftLeft=45;b.ShiftRight=46;b.ControlLeft=47;b.ControlRight=48;b.AltLeft=49;b.AltRight=50;for(c=1;12>=c;c++)b["F"+c]=50+c;b.Delete=63;b.Insert=64;b.Home=65;b.End=66;b.PageUp=67;
b.PageDown=68;var d={Space:1,Tab:1,ArrowUp:1,ArrowDown:1,ArrowLeft:1,ArrowRight:1,F1:1,F2:1,F3:1,F4:1,F6:1,F7:1,F8:1,F9:1,F10:1},f=a.getBoundingClientRect();(new ResizeObserver(function(){f=a.getBoundingClientRect()})).observe(a);g._ntKeyBuf=[];g._ntPtrBuf=[];g._ntWheelBuf=[];g._ntBlurred=!1;a.addEventListener("keydown",function(e){if(!e.repeat){var h=b[e.code];void 0!==h&&g._ntKeyBuf.push(h,1);d[e.code]&&e.preventDefault()}});a.addEventListener("keyup",function(e){e=b[e.code];void 0!==e&&g._ntKeyBuf.push(e,
0)});a.addEventListener("blur",function(){g._ntBlurred=!0});a.addEventListener("pointerdown",function(e){a.focus();a.setPointerCapture(e.pointerId);g._ntPtrBuf.push(0,e.pointerId,e.clientX-f.left,e.clientY-f.top,e.pressure,"touch"===e.pointerType?1:"pen"===e.pointerType?2:0,e.buttons);e.preventDefault()});a.addEventListener("pointermove",function(e){g._ntPtrBuf.push(1,e.pointerId,e.clientX-f.left,e.clientY-f.top,e.pressure,"touch"===e.pointerType?1:"pen"===e.pointerType?2:0,e.buttons)});a.addEventListener("pointerup",
function(e){"mouse"===e.pointerType?g._ntPtrBuf.push(1,e.pointerId,e.clientX-f.left,e.clientY-f.top,e.pressure,0,e.buttons):g._ntPtrBuf.push(2,e.pointerId,0,0,0,0,0);e.preventDefault()});a.addEventListener("pointercancel",function(e){g._ntPtrBuf.push(2,e.pointerId,0,0,0,0,0);e.preventDefault()});a.addEventListener("pointerleave",function(e){"mouse"===e.pointerType&&g._ntPtrBuf.push(2,e.pointerId,0,0,0,0,0)});a.addEventListener("wheel",function(e){var h=e.deltaX,l=e.deltaY;1===e.deltaMode?(h*=16,l*=
16):2===e.deltaMode&&(h*=window.innerWidth,l*=window.innerHeight);g._ntWheelBuf.push(h,l);e.preventDefault()},{passive:!1});a.style.touchAction="none"},ka:function(){var a=document.getElementById("spinner");a&&(a.style.display="none")},F:function(){return g.canvas.clientHeight},M:function(){return g.canvas.clientWidth},x:function(){return window.devicePixelRatio||1},s:function(a,b){g.canvas.width=a;g.canvas.height=b}},Z=function(){function a(c){Z=c.exports;H=Z.la;oa();Sa=Z.na;qa.unshift(Z.ma);M--;
g.monitorRunDependencies?.(M);0==M&&(null!==ua&&(clearInterval(ua),ua=null),N&&(c=N,N=null,c()));return Z}var b={a:ab};M++;g.monitorRunDependencies?.(M);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return E(`Module.instantiateWasm callback failed with error: ${c}`),!1}Aa(b,function(c){a(c.instance)});return{}}(),bb=g._main=(a,b)=>(bb=g._main=Z.oa)(a,b);g._nt_input_web_on_key=(a,b)=>(g._nt_input_web_on_key=Z.pa)(a,b);
g._nt_input_web_on_pointer_down=(a,b,c,d,f,e)=>(g._nt_input_web_on_pointer_down=Z.qa)(a,b,c,d,f,e);g._nt_input_web_on_pointer_move=(a,b,c,d,f,e)=>(g._nt_input_web_on_pointer_move=Z.ra)(a,b,c,d,f,e);g._nt_input_web_on_pointer_up=a=>(g._nt_input_web_on_pointer_up=Z.sa)(a);g._nt_input_web_on_wheel=(a,b)=>(g._nt_input_web_on_wheel=Z.ta)(a,b);g._nt_input_web_on_blur=()=>(g._nt_input_web_on_blur=Z.ua)();g._free=a=>(g._free=Z.va)(a);
g._nt_http_web_on_progress=(a,b,c,d)=>(g._nt_http_web_on_progress=Z.wa)(a,b,c,d);g._nt_http_web_on_complete=(a,b,c,d,f)=>(g._nt_http_web_on_complete=Z.xa)(a,b,c,d,f);g._malloc=a=>(g._malloc=Z.ya)(a);g.___start_em_js=10180;g.___stop_em_js=16948;var cb;N=function db(){cb||eb();cb||(N=db)};
function eb(){function a(){if(!cb&&(cb=!0,g.calledRun=!0,!ia)){P(qa);P(ra);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(fb){var b=bb;try{var c=b(0,0);Ba||(g.onExit?.(c),ia=!0);k(c,new D(c))}catch(d){d instanceof D||"unwind"==d||k(1,d)}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)b=g.postRun.shift(),sa.unshift(b);P(sa)}}if(!(0<M)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)ta();P(pa);0<M||(g.setStatus?(g.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var fb=!0;g.noInitialRun&&(fb=!1);eb();
