var e;e||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},e),h=(a,b)=>{throw b;},ba="object"==typeof window,l="function"==typeof importScripts,da="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",r,t,u;
if(da){var fs=require("fs"),v=require("path");q=l?v.dirname(q)+"/":__dirname+"/";r=(a,b)=>{a=w(a)?new URL(a):v.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};u=a=>{a=r(a,!0);a.buffer||(a=new Uint8Array(a));return a};t=(a,b,c,d=!0)=>{a=w(a)?new URL(a):v.normalize(a);fs.readFile(a,d?void 0:"utf8",(g,f)=>{g?c(g):b(d?f.buffer:f)})};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof x||a.context instanceof x))throw a;
});h=(a,b)=>{process.exitCode=a;throw b;};e.inspect=()=>"[Emscripten Module object]"}else if(ba||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",r=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(u=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
t=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ea=e.print||console.log.bind(console),y=e.printErr||console.error.bind(console);Object.assign(e,aa);aa=null;e.quit&&(h=e.quit);var z;e.wasmBinary&&(z=e.wasmBinary);"object"!=typeof WebAssembly&&fa("no native wasm support detected");var A,B=!1,ha,C,ia,ja,D,E,F;
function ka(){var a=A.buffer;e.HEAP8=ha=new Int8Array(a);e.HEAP16=ia=new Int16Array(a);e.HEAPU8=C=new Uint8Array(a);e.HEAPU16=ja=new Uint16Array(a);e.HEAP32=D=new Int32Array(a);e.HEAPU32=E=new Uint32Array(a);e.HEAPF32=F=new Float32Array(a);e.HEAPF64=new Float64Array(a)}var la=[],ma=[],na=[],oa=[];function pa(){var a=e.preRun.shift();la.unshift(a)}var G=0,H=null,I=null;
function fa(a){e.onAbort?.(a);a="Aborted("+a+")";y(a);B=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var qa=a=>a.startsWith("data:application/octet-stream;base64,"),w=a=>a.startsWith("file://"),J;J="index.wasm";if(!qa(J)){var ra=J;J=e.locateFile?e.locateFile(ra,q):q+ra}function sa(a){if(a==J&&z)return new Uint8Array(z);if(u)return u(a);throw"both async and sync fetching of the wasm failed";}
function ta(a){if(!z&&(ba||l)){if("function"==typeof fetch&&!w(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>sa(a));if(t)return new Promise((b,c)=>{t(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>sa(a))}function ua(a,b,c){return ta(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{y(`failed to asynchronously prepare wasm: ${d}`);fa(d)})}
function va(a,b){var c=J;z||"function"!=typeof WebAssembly.instantiateStreaming||qa(c)||w(c)||da||"function"!=typeof fetch?ua(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(g){y(`wasm streaming compile failed: ${g}`);y("falling back to ArrayBuffer instantiation");return ua(c,a,b)}))}function x(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var K=a=>{for(;0<a.length;)a.shift()(e)},wa=e.noExitRuntime||!0,xa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,L=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&xa)return xa.decode(a.subarray(b,c));for(d="";b<c;){var g=a[b++];if(g&128){var f=a[b++]&63;if(192==(g&224))d+=String.fromCharCode((g&31)<<6|f);else{var k=a[b++]&63;g=224==(g&240)?(g&15)<<12|f<<6|k:(g&7)<<18|f<<12|k<<6|a[b++]&63;65536>g?d+=String.fromCharCode(g):(g-=65536,d+=String.fromCharCode(55296|
g>>10,56320|g&1023))}}else d+=String.fromCharCode(g)}return d},ya=1,M=[],N=[],O=[],P=[],Q=[],R=[];function S(a){za||=a}
var T=a=>{for(var b=ya++,c=a.length;c<b;c++)a[c]=null;return b},Ba=(a,b)=>{a.Ea||(a.Ea=a.getContext,a.getContext=function(d,g){g=a.Ea(d,g);return"webgl"==d==g instanceof WebGLRenderingContext?g:null});var c=a.getContext("webgl2",b);return c?Aa(c,b):0},Aa=(a,b)=>{var c=T(R),d={handle:c,attributes:b,version:b.La,ua:a};a.canvas&&(a.canvas.Ha=d);R[c]=d;("undefined"==typeof b.Da||b.Da)&&Ca(d);return c},Ca=a=>{a||=U;if(!a.Ka){a.Ka=!0;var b=a.ua;b.Na=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");
b.Qa=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Ca=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Ca)b.Ca=b.getExtension("EXT_disjoint_timer_query");b.Sa=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},za,U,V=[],Da,W=[],Ea={},Fa=["default","low-power","high-performance"],Ga=[0,"undefined"!=typeof document?document:0,"undefined"!=
typeof window?window:0],Ha=[null,[],[]],Ia=(a,b,c,d)=>{for(var g=0;g<a;g++){var f=X[c](),k=f&&T(d);f?(f.name=k,d[k]=f):S(1282);D[b+4*g>>2]=k}},Ja=(a,b,c)=>{var d=C;if(!(0<c))return 0;var g=b;c=b+c-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var m=a.charCodeAt(++f);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(b>=c)break;d[b++]=k}else{if(2047>=k){if(b+1>=c)break;d[b++]=192|k>>6}else{if(65535>=k){if(b+2>=c)break;d[b++]=224|k>>12}else{if(b+3>=c)break;d[b++]=240|k>>18;d[b++]=
128|k>>12&63}d[b++]=128|k>>6&63}d[b++]=128|k&63}}d[b]=0;return b-g},Ka=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),La=a=>{var b=X.Ia;if(b){var c=b.va[a];"number"==typeof c&&(b.va[a]=c=X.getUniformLocation(b,b.Fa[a]+(0<c?`[${c}]`:"")));return c}S(1282)},X,Ma={w:a=>!R[a]||R[a].ua.isContextLost(),v:(a,b,c)=>C.copyWithin(a,b,b+c),ia:(a,b)=>{function c(d){var g=V[a];g||(a>=V.length&&(V.length=a+1),V[a]=g=Da.get(a));g(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},s:a=>{var b=C.length;a>>>=
0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var g=Math;d=Math.max(a,d);a:{g=(g.min.call(g,2147483648,d+(65536-d%65536)%65536)-A.buffer.byteLength+65535)/65536;try{A.grow(g);ka();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},z:(a,b)=>{b>>=2;b={alpha:!!D[b],depth:!!D[b+1],stencil:!!D[b+2],antialias:!!D[b+3],premultipliedAlpha:!!D[b+4],preserveDrawingBuffer:!!D[b+5],powerPreference:Fa[D[b+6]],failIfMajorPerformanceCaveat:!!D[b+7],La:D[b+8],
Ra:D[b+9],Da:D[b+10],Ja:D[b+11],Ta:D[b+12],Ua:D[b+13]};a=2<a?a?L(C,a):"":a;a=Ga[a]||("undefined"!=typeof document?document.querySelector(a):void 0);return!a||b.Ja?0:Ba(a,b)},x:a=>{U==a&&(U=0);U===R[a]&&(U=null);if("object"==typeof Ea)for(var b=R[a].ua.canvas,c=0;c<W.length;++c)if(W[c].target==b){var d=c--,g=W[d];g.target.removeEventListener(g.Pa,g.Oa,g.Va);W.splice(d,1)}R[a]&&R[a].ua.canvas&&(R[a].ua.canvas.Ha=void 0);R[a]=null},A:a=>{a>>=2;for(var b=0;14>b;++b)D[a+b]=0;D[a]=D[a+1]=D[a+3]=D[a+4]=
D[a+8]=D[a+10]=1},y:a=>{U=R[a];e.Ma=X=U?.ua;return!a||X?0:-5},t:()=>52,r:function(){return 70},i:(a,b,c,d)=>{for(var g=0,f=0;f<c;f++){var k=E[b>>2],m=E[b+4>>2];b+=8;for(var p=0;p<m;p++){var n=C[k+p],ca=Ha[a];0===n||10===n?((1===a?ea:y)(L(ca,0)),ca.length=0):ca.push(n)}g+=m}E[d>>2]=g;return 0},n:(a,b)=>{X.attachShader(N[a],P[b])},a:(a,b)=>{35051==a?X.Ba=b:35052==a&&(X.za=b);X.bindBuffer(a,M[b])},G:(a,b)=>{X.bindTexture(a,O[b])},h:a=>{X.bindVertexArray(Q[a])},ba:function(a,b){X.blendFunc(a,b)},J:(a,
b,c,d)=>{c&&b?X.bufferData(a,C,d,c,b):X.bufferData(a,b,d)},I:(a,b,c,d)=>{c&&X.bufferSubData(a,b,C,d,c)},ga:function(a){X.clear(a)},o:function(a,b,c,d){X.clearColor(a,b,c,d)},ha:function(a){X.clearDepth(a)},U:a=>{X.compileShader(P[a])},S:()=>{var a=T(N),b=X.createProgram();b.name=a;b.ya=b.wa=b.xa=0;b.Aa=1;N[a]=b;return a},W:a=>{var b=T(P);P[b]=X.createShader(a);return b},ca:function(a){X.cullFace(a)},k:(a,b)=>{for(var c=0;c<a;c++){var d=D[b+4*c>>2],g=M[d];g&&(X.deleteBuffer(g),g.name=0,M[d]=null,d==
X.Ba&&(X.Ba=0),d==X.za&&(X.za=0))}},e:a=>{if(a){var b=N[a];b?(X.deleteProgram(b),b.name=0,N[a]=null):S(1281)}},f:a=>{if(a){var b=P[a];b?(X.deleteShader(b),P[a]=null):S(1281)}},C:(a,b)=>{for(var c=0;c<a;c++){var d=D[b+4*c>>2],g=O[d];g&&(X.deleteTexture(g),g.name=0,O[d]=null)}},L:(a,b)=>{for(var c=0;c<a;c++){var d=D[b+4*c>>2];X.deleteVertexArray(Q[d]);Q[d]=null}},ea:function(a){X.depthFunc(a)},da:a=>{X.depthMask(!!a)},c:function(a){X.disable(a)},X:(a,b,c,d)=>{X.drawElements(a,b,c,d)},B:(a,b,c,d,g)=>
{X.drawElementsInstanced(a,b,c,d,g)},d:function(a){X.enable(a)},m:a=>{X.enableVertexAttribArray(a)},K:(a,b)=>{Ia(a,b,"createBuffer",M)},H:(a,b)=>{Ia(a,b,"createTexture",O)},P:function(a,b){Ia(a,b,"createVertexArray",Q)},D:function(a){X.generateMipmap(a)},N:(a,b,c,d)=>{a=X.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ja(a,d,b):0;c&&(D[c>>2]=b)},Q:(a,b,c)=>{if(c)if(a>=ya)S(1281);else if(a=N[a],35716==b)a=X.getProgramInfoLog(a),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1;else if(35719==
b){if(!a.ya)for(b=0;b<X.getProgramParameter(a,35718);++b)a.ya=Math.max(a.ya,X.getActiveUniform(a,b).name.length+1);D[c>>2]=a.ya}else if(35722==b){if(!a.wa)for(b=0;b<X.getProgramParameter(a,35721);++b)a.wa=Math.max(a.wa,X.getActiveAttrib(a,b).name.length+1);D[c>>2]=a.wa}else if(35381==b){if(!a.xa)for(b=0;b<X.getProgramParameter(a,35382);++b)a.xa=Math.max(a.xa,X.getActiveUniformBlockName(a,b).length+1);D[c>>2]=a.xa}else D[c>>2]=X.getProgramParameter(a,b);else S(1281)},l:(a,b,c,d)=>{a=X.getShaderInfoLog(P[a]);
null===a&&(a="(unknown error)");b=0<b&&d?Ja(a,d,b):0;c&&(D[c>>2]=b)},g:(a,b)=>{b=b?L(C,b):"";if(a=N[a]){var c=a,d=c.va,g=c.Ga,f;if(!d)for(c.va=d={},c.Fa={},f=0;f<X.getProgramParameter(c,35718);++f){var k=X.getActiveUniform(c,f);var m=k.name;k=k.size;var p=Ka(m);p=0<p?m.slice(0,p):m;var n=c.Aa;c.Aa+=k;g[p]=[k,n];for(m=0;m<k;++m)d[n]=m,c.Fa[n++]=p}c=a.va;d=0;g=b;f=Ka(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,g=b.slice(0,f));if((g=a.Ga[g])&&d<g[0]&&(d+=g[1],c[d]=c[d]||X.getUniformLocation(a,b)))return d}else S(1281);
return-1},R:a=>{a=N[a];X.linkProgram(a);a.va=0;a.Ga={}},$:function(a,b){X.polygonOffset(a,b)},V:(a,b,c,d)=>{for(var g="",f=0;f<b;++f){var k=d?D[d+4*f>>2]:-1,m=D[c+4*f>>2];k=m?L(C,m,0>k?void 0:k):"";g+=k}X.shaderSource(P[a],g)},E:(a,b,c,d,g,f,k,m,p)=>{if(X.za)X.texImage2D(a,b,c,d,g,f,k,m,p);else if(p){var n=m-5120;n=0==n?ha:1==n?C:2==n?ia:4==n?D:6==n?F:5==n||28922==n||28520==n||30779==n||30782==n?E:ja;X.texImage2D(a,b,c,d,g,f,k,m,n,p>>31-Math.clz32(n.BYTES_PER_ELEMENT))}else X.texImage2D(a,b,c,d,g,
f,k,m,null)},b:function(a,b,c){X.texParameteri(a,b,c)},Y:(a,b)=>{X.uniform1f(La(a),b)},Z:(a,b,c)=>{b&&X.uniform4fv(La(a),F,c>>2,4*b)},_:(a,b,c,d)=>{b&&X.uniformMatrix4fv(La(a),!!c,F,d>>2,16*b)},fa:a=>{a=N[a];X.useProgram(a);X.Ia=a},O:(a,b)=>{X.vertexAttribDivisor(a,b)},j:(a,b,c,d,g,f)=>{X.vertexAttribPointer(a,b,c,!!d,g,f)},p:function(a,b,c,d){X.viewport(a,b,c,d)},T:function(){if(e._ntBlurred)e._nt_input_web_on_blur(),e._ntBlurred=!1,e._ntKeyBuf.length=0,e._ntPtrBuf.length=0,e._ntWheelBuf.length=
0;else{for(var a=e._ntKeyBuf,b=0;b<a.length;b+=2)e._nt_input_web_on_key(a[b],a[b+1]);a.length=0;a=e._ntPtrBuf;for(b=0;b<a.length;b+=7)0===a[b]?e._nt_input_web_on_pointer_down(a[b+1],a[b+2],a[b+3],a[b+4],a[b+5],a[b+6]):1===a[b]?e._nt_input_web_on_pointer_move(a[b+1],a[b+2],a[b+3],a[b+4],a[b+5],a[b+6]):e._nt_input_web_on_pointer_up(a[b+1]);a.length=0;a=e._ntWheelBuf;for(b=0;b<a.length;b+=2)e._nt_input_web_on_wheel(a[b],a[b+1]);a.length=0}},aa:function(){for(var a=e.canvas,b={},c=0;26>c;c++)b["Key"+
"ABCDEFGHIJKLMNOPQRSTUVWXYZ"[c]]=c;for(c=0;10>c;c++)b["Digit"+c]=26+c;b.ArrowUp=36;b.ArrowDown=37;b.ArrowLeft=38;b.ArrowRight=39;b.Space=40;b.Enter=41;b.Escape=42;b.Tab=43;b.Backspace=44;b.ShiftLeft=45;b.ShiftRight=46;b.ControlLeft=47;b.ControlRight=48;b.AltLeft=49;b.AltRight=50;for(c=1;12>=c;c++)b["F"+c]=50+c;b.Delete=63;b.Insert=64;b.Home=65;b.End=66;b.PageUp=67;b.PageDown=68;var d={Space:1,Tab:1,ArrowUp:1,ArrowDown:1,ArrowLeft:1,ArrowRight:1,F1:1,F2:1,F3:1,F4:1,F6:1,F7:1,F8:1,F9:1,F10:1},g=a.getBoundingClientRect();
(new ResizeObserver(function(){g=a.getBoundingClientRect()})).observe(a);e._ntKeyBuf=[];e._ntPtrBuf=[];e._ntWheelBuf=[];e._ntBlurred=!1;a.addEventListener("keydown",function(f){if(!f.repeat){var k=b[f.code];void 0!==k&&e._ntKeyBuf.push(k,1);d[f.code]&&f.preventDefault()}});a.addEventListener("keyup",function(f){f=b[f.code];void 0!==f&&e._ntKeyBuf.push(f,0)});a.addEventListener("blur",function(){e._ntBlurred=!0});a.addEventListener("pointerdown",function(f){a.focus();a.setPointerCapture(f.pointerId);
e._ntPtrBuf.push(0,f.pointerId,f.clientX-g.left,f.clientY-g.top,f.pressure,"touch"===f.pointerType?1:"pen"===f.pointerType?2:0,f.buttons);f.preventDefault()});a.addEventListener("pointermove",function(f){e._ntPtrBuf.push(1,f.pointerId,f.clientX-g.left,f.clientY-g.top,f.pressure,"touch"===f.pointerType?1:"pen"===f.pointerType?2:0,f.buttons)});a.addEventListener("pointerup",function(f){"mouse"===f.pointerType?e._ntPtrBuf.push(1,f.pointerId,f.clientX-g.left,f.clientY-g.top,f.pressure,0,f.buttons):e._ntPtrBuf.push(2,
f.pointerId,0,0,0,0,0);f.preventDefault()});a.addEventListener("pointercancel",function(f){e._ntPtrBuf.push(2,f.pointerId,0,0,0,0,0);f.preventDefault()});a.addEventListener("pointerleave",function(f){"mouse"===f.pointerType&&e._ntPtrBuf.push(2,f.pointerId,0,0,0,0,0)});a.addEventListener("wheel",function(f){var k=f.deltaX,m=f.deltaY;1===f.deltaMode?(k*=16,m*=16):2===f.deltaMode&&(k*=window.innerWidth,m*=window.innerHeight);e._ntWheelBuf.push(k,m);f.preventDefault()},{passive:!1});a.style.touchAction=
"none"},ja:function(){var a=document.getElementById("spinner");a&&(a.style.display="none")},F:function(){return e.canvas.clientHeight},M:function(){return e.canvas.clientWidth},u:function(){return window.devicePixelRatio||1},q:function(a,b){e.canvas.width=a;e.canvas.height=b}},Y=function(){function a(c){Y=c.exports;A=Y.ka;ka();Da=Y.ma;ma.unshift(Y.la);G--;e.monitorRunDependencies?.(G);0==G&&(null!==H&&(clearInterval(H),H=null),I&&(c=I,I=null,c()));return Y}var b={a:Ma};G++;e.monitorRunDependencies?.(G);
if(e.instantiateWasm)try{return e.instantiateWasm(b,a)}catch(c){return y(`Module.instantiateWasm callback failed with error: ${c}`),!1}va(b,function(c){a(c.instance)});return{}}(),Na=e._main=(a,b)=>(Na=e._main=Y.na)(a,b);e._nt_input_web_on_key=(a,b)=>(e._nt_input_web_on_key=Y.oa)(a,b);e._nt_input_web_on_pointer_down=(a,b,c,d,g,f)=>(e._nt_input_web_on_pointer_down=Y.pa)(a,b,c,d,g,f);e._nt_input_web_on_pointer_move=(a,b,c,d,g,f)=>(e._nt_input_web_on_pointer_move=Y.qa)(a,b,c,d,g,f);
e._nt_input_web_on_pointer_up=a=>(e._nt_input_web_on_pointer_up=Y.ra)(a);e._nt_input_web_on_wheel=(a,b)=>(e._nt_input_web_on_wheel=Y.sa)(a,b);e._nt_input_web_on_blur=()=>(e._nt_input_web_on_blur=Y.ta)();e.___start_em_js=10564;e.___stop_em_js=14936;var Z;I=function Oa(){Z||Pa();Z||(I=Oa)};
function Pa(){function a(){if(!Z&&(Z=!0,e.calledRun=!0,!B)){K(ma);K(na);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Qa){var b=Na;try{var c=b(0,0);wa||(e.onExit?.(c),B=!0);h(c,new x(c))}catch(d){d instanceof x||"unwind"==d||h(1,d)}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)b=e.postRun.shift(),oa.unshift(b);K(oa)}}if(!(0<G)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)pa();K(la);0<G||(e.setStatus?(e.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Qa=!0;e.noInitialRun&&(Qa=!1);Pa();
