var e;e||=typeof Module !== 'undefined' ? Module : {};var ba=Object.assign({},e),h=(a,b)=>{throw b;},ca="object"==typeof window,l="function"==typeof importScripts,da="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,n="",p,q,r;
if(da){var fs=require("fs"),t=require("path");n=l?t.dirname(n)+"/":__dirname+"/";p=(a,b)=>{a=v(a)?new URL(a):t.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};r=a=>{a=p(a,!0);a.buffer||(a=new Uint8Array(a));return a};q=(a,b,c,d=!0)=>{a=v(a)?new URL(a):t.normalize(a);fs.readFile(a,d?void 0:"utf8",(g,f)=>{g?c(g):b(d?f.buffer:f)})};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof w||a.context instanceof w))throw a;
});h=(a,b)=>{process.exitCode=a;throw b;};e.inspect=()=>"[Emscripten Module object]"}else if(ca||l)l?n=self.location.href:"undefined"!=typeof document&&document.currentScript&&(n=document.currentScript.src),n=0!==n.indexOf("blob:")?n.substr(0,n.replace(/[?#].*/,"").lastIndexOf("/")+1):"",p=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(r=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
q=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ea=e.print||console.log.bind(console),x=e.printErr||console.error.bind(console);Object.assign(e,ba);ba=null;e.quit&&(h=e.quit);var y;e.wasmBinary&&(y=e.wasmBinary);"object"!=typeof WebAssembly&&fa("no native wasm support detected");var A,B=!1,C,D,E,F;
function ha(){var a=A.buffer;e.HEAP8=new Int8Array(a);e.HEAP16=new Int16Array(a);e.HEAPU8=C=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAP32=D=new Int32Array(a);e.HEAPU32=E=new Uint32Array(a);e.HEAPF32=F=new Float32Array(a);e.HEAPF64=new Float64Array(a)}var ia=[],ja=[],ka=[],la=[];function ma(){var a=e.preRun.shift();ia.unshift(a)}var G=0,H=null,I=null;
function fa(a){e.onAbort?.(a);a="Aborted("+a+")";x(a);B=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var na=a=>a.startsWith("data:application/octet-stream;base64,"),v=a=>a.startsWith("file://"),J;J="index.wasm";if(!na(J)){var oa=J;J=e.locateFile?e.locateFile(oa,n):n+oa}function pa(a){if(a==J&&y)return new Uint8Array(y);if(r)return r(a);throw"both async and sync fetching of the wasm failed";}
function qa(a){if(!y&&(ca||l)){if("function"==typeof fetch&&!v(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>pa(a));if(q)return new Promise((b,c)=>{q(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>pa(a))}function ra(a,b,c){return qa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{x(`failed to asynchronously prepare wasm: ${d}`);fa(d)})}
function sa(a,b){var c=J;y||"function"!=typeof WebAssembly.instantiateStreaming||na(c)||v(c)||da||"function"!=typeof fetch?ra(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(g){x(`wasm streaming compile failed: ${g}`);x("falling back to ArrayBuffer instantiation");return ra(c,a,b)}))}function w(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var K=a=>{for(;0<a.length;)a.shift()(e)},ta=e.noExitRuntime||!0,ua="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,L=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ua)return ua.decode(a.subarray(b,c));for(d="";b<c;){var g=a[b++];if(g&128){var f=a[b++]&63;if(192==(g&224))d+=String.fromCharCode((g&31)<<6|f);else{var k=a[b++]&63;g=224==(g&240)?(g&15)<<12|f<<6|k:(g&7)<<18|f<<12|k<<6|a[b++]&63;65536>g?d+=String.fromCharCode(g):(g-=65536,d+=String.fromCharCode(55296|
g>>10,56320|g&1023))}}else d+=String.fromCharCode(g)}return d},va=1,M=[],N=[],O=[],P=[],Q=[];function R(a){wa||=a}
var S=a=>{for(var b=va++,c=a.length;c<b;c++)a[c]=null;return b},ya=(a,b)=>{a.ya||(a.ya=a.getContext,a.getContext=function(d,g){g=a.ya(d,g);return"webgl"==d==g instanceof WebGLRenderingContext?g:null});var c=a.getContext("webgl2",b);return c?xa(c,b):0},xa=(a,b)=>{var c=S(Q),d={handle:c,attributes:b,version:b.Fa,oa:a};a.canvas&&(a.canvas.Ba=d);Q[c]=d;("undefined"==typeof b.xa||b.xa)&&za(d);return c},za=a=>{a||=T;if(!a.Ea){a.Ea=!0;var b=a.oa;b.Ha=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");
b.Ka=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.wa=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.wa)b.wa=b.getExtension("EXT_disjoint_timer_query");b.Ma=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},wa,T,U=[],Aa,V=[],Ba={},Ca=["default","low-power","high-performance"],Da=[0,"undefined"!=typeof document?document:0,"undefined"!=
typeof window?window:0],Ea=[null,[],[]],Fa=(a,b,c,d)=>{for(var g=0;g<a;g++){var f=W[c](),k=f&&S(d);f?(f.name=k,d[k]=f):R(1282);D[b+4*g>>2]=k}},Ga=(a,b,c)=>{var d=C;if(!(0<c))return 0;var g=b;c=b+c-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var m=a.charCodeAt(++f);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(b>=c)break;d[b++]=k}else{if(2047>=k){if(b+1>=c)break;d[b++]=192|k>>6}else{if(65535>=k){if(b+2>=c)break;d[b++]=224|k>>12}else{if(b+3>=c)break;d[b++]=240|k>>18;d[b++]=
128|k>>12&63}d[b++]=128|k>>6&63}d[b++]=128|k&63}}d[b]=0;return b-g},Ha=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),X=a=>{var b=W.Ca;if(b){var c=b.pa[a];"number"==typeof c&&(b.pa[a]=c=W.getUniformLocation(b,b.za[a]+(0<c?`[${c}]`:"")));return c}R(1282)},W,Ia={u:a=>!Q[a]||Q[a].oa.isContextLost(),t:(a,b,c)=>C.copyWithin(a,b,b+c),ca:(a,b)=>{function c(d){var g=U[a];g||(a>=U.length&&(U.length=a+1),U[a]=g=Aa.get(a));g(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},r:a=>{var b=C.length;a>>>=
0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var g=Math;d=Math.max(a,d);a:{g=(g.min.call(g,2147483648,d+(65536-d%65536)%65536)-A.buffer.byteLength+65535)/65536;try{A.grow(g);ha();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},y:(a,b)=>{b>>=2;b={alpha:!!D[b],depth:!!D[b+1],stencil:!!D[b+2],antialias:!!D[b+3],premultipliedAlpha:!!D[b+4],preserveDrawingBuffer:!!D[b+5],powerPreference:Ca[D[b+6]],failIfMajorPerformanceCaveat:!!D[b+7],Fa:D[b+8],
La:D[b+9],xa:D[b+10],Da:D[b+11],Na:D[b+12],Oa:D[b+13]};a=2<a?a?L(C,a):"":a;a=Da[a]||("undefined"!=typeof document?document.querySelector(a):void 0);return!a||b.Da?0:ya(a,b)},v:a=>{T==a&&(T=0);T===Q[a]&&(T=null);if("object"==typeof Ba)for(var b=Q[a].oa.canvas,c=0;c<V.length;++c)if(V[c].target==b){var d=c--,g=V[d];g.target.removeEventListener(g.Ja,g.Ia,g.Pa);V.splice(d,1)}Q[a]&&Q[a].oa.canvas&&(Q[a].oa.canvas.Ba=void 0);Q[a]=null},z:a=>{a>>=2;for(var b=0;14>b;++b)D[a+b]=0;D[a]=D[a+1]=D[a+3]=D[a+4]=
D[a+8]=D[a+10]=1},w:a=>{T=Q[a];e.Ga=W=T?.oa;return!a||W?0:-5},s:()=>52,q:function(){return 70},g:(a,b,c,d)=>{for(var g=0,f=0;f<c;f++){var k=E[b>>2],m=E[b+4>>2];b+=8;for(var u=0;u<m;u++){var z=C[k+u],aa=Ea[a];0===z||10===z?((1===a?ea:x)(L(aa,0)),aa.length=0):aa.push(z)}g+=m}E[d>>2]=g;return 0},l:(a,b)=>{W.attachShader(N[a],O[b])},a:(a,b)=>{35051==a?W.ua=b:35052==a&&(W.va=b);W.bindBuffer(a,M[b])},f:a=>{W.bindVertexArray(P[a])},X:function(a,b){W.blendFunc(a,b)},C:(a,b,c,d)=>{c&&b?W.bufferData(a,C,d,
c,b):W.bufferData(a,b,d)},B:(a,b,c,d)=>{c&&W.bufferSubData(a,b,C,d,c)},aa:function(a){W.clear(a)},m:function(a,b,c,d){W.clearColor(a,b,c,d)},ba:function(a){W.clearDepth(a)},O:a=>{W.compileShader(O[a])},L:()=>{var a=S(N),b=W.createProgram();b.name=a;b.sa=b.qa=b.ra=0;b.ta=1;N[a]=b;return a},Q:a=>{var b=S(O);O[b]=W.createShader(a);return b},Y:function(a){W.cullFace(a)},i:(a,b)=>{for(var c=0;c<a;c++){var d=D[b+4*c>>2],g=M[d];g&&(W.deleteBuffer(g),g.name=0,M[d]=null,d==W.ua&&(W.ua=0),d==W.va&&(W.va=0))}},
d:a=>{if(a){var b=N[a];b?(W.deleteProgram(b),b.name=0,N[a]=null):R(1281)}},N:a=>{if(a){var b=O[a];b?(W.deleteShader(b),O[a]=null):R(1281)}},E:(a,b)=>{for(var c=0;c<a;c++){var d=D[b+4*c>>2];W.deleteVertexArray(P[d]);P[d]=null}},_:function(a){W.depthFunc(a)},Z:a=>{W.depthMask(!!a)},b:function(a){W.disable(a)},R:(a,b,c,d)=>{W.drawElements(a,b,c,d)},A:(a,b,c,d,g)=>{W.drawElementsInstanced(a,b,c,d,g)},c:function(a){W.enable(a)},k:a=>{W.enableVertexAttribArray(a)},D:(a,b)=>{Fa(a,b,"createBuffer",M)},I:function(a,
b){Fa(a,b,"createVertexArray",P)},G:(a,b,c,d)=>{a=W.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ga(a,d,b):0;c&&(D[c>>2]=b)},J:(a,b,c)=>{if(c)if(a>=va)R(1281);else if(a=N[a],35716==b)a=W.getProgramInfoLog(a),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1;else if(35719==b){if(!a.sa)for(b=0;b<W.getProgramParameter(a,35718);++b)a.sa=Math.max(a.sa,W.getActiveUniform(a,b).name.length+1);D[c>>2]=a.sa}else if(35722==b){if(!a.qa)for(b=0;b<W.getProgramParameter(a,35721);++b)a.qa=Math.max(a.qa,
W.getActiveAttrib(a,b).name.length+1);D[c>>2]=a.qa}else if(35381==b){if(!a.ra)for(b=0;b<W.getProgramParameter(a,35382);++b)a.ra=Math.max(a.ra,W.getActiveUniformBlockName(a,b).length+1);D[c>>2]=a.ra}else D[c>>2]=W.getProgramParameter(a,b);else R(1281)},j:(a,b,c,d)=>{a=W.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ga(a,d,b):0;c&&(D[c>>2]=b)},e:(a,b)=>{b=b?L(C,b):"";if(a=N[a]){var c=a,d=c.pa,g=c.Aa,f;if(!d)for(c.pa=d={},c.za={},f=0;f<W.getProgramParameter(c,35718);++f){var k=W.getActiveUniform(c,
f);var m=k.name;k=k.size;var u=Ha(m);u=0<u?m.slice(0,u):m;var z=c.ta;c.ta+=k;g[u]=[k,z];for(m=0;m<k;++m)d[z]=m,c.za[z++]=u}c=a.pa;d=0;g=b;f=Ha(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,g=b.slice(0,f));if((g=a.Aa[g])&&d<g[0]&&(d+=g[1],c[d]=c[d]||W.getUniformLocation(a,b)))return d}else R(1281);return-1},K:a=>{a=N[a];W.linkProgram(a);a.pa=0;a.Aa={}},V:function(a,b){W.polygonOffset(a,b)},P:(a,b,c,d)=>{for(var g="",f=0;f<b;++f){var k=d?D[d+4*f>>2]:-1,m=D[c+4*f>>2];k=m?L(C,m,0>k?void 0:k):"";g+=k}W.shaderSource(O[a],
g)},S:(a,b)=>{W.uniform1f(X(a),b)},T:(a,b,c)=>{b&&W.uniform4fv(X(a),F,c>>2,4*b)},U:(a,b,c,d)=>{b&&W.uniformMatrix4fv(X(a),!!c,F,d>>2,16*b)},$:a=>{a=N[a];W.useProgram(a);W.Ca=a},H:(a,b)=>{W.vertexAttribDivisor(a,b)},h:(a,b,c,d,g,f)=>{W.vertexAttribPointer(a,b,c,!!d,g,f)},n:function(a,b,c,d){W.viewport(a,b,c,d)},M:function(){if(e._ntBlurred)e._nt_input_web_on_blur(),e._ntBlurred=!1,e._ntKeyBuf.length=0,e._ntPtrBuf.length=0,e._ntWheelBuf.length=0;else{for(var a=e._ntKeyBuf,b=0;b<a.length;b+=2)e._nt_input_web_on_key(a[b],
a[b+1]);a.length=0;a=e._ntPtrBuf;for(b=0;b<a.length;b+=7)0===a[b]?e._nt_input_web_on_pointer_down(a[b+1],a[b+2],a[b+3],a[b+4],a[b+5],a[b+6]):1===a[b]?e._nt_input_web_on_pointer_move(a[b+1],a[b+2],a[b+3],a[b+4],a[b+5],a[b+6]):e._nt_input_web_on_pointer_up(a[b+1]);a.length=0;a=e._ntWheelBuf;for(b=0;b<a.length;b+=2)e._nt_input_web_on_wheel(a[b],a[b+1]);a.length=0}},W:function(){for(var a=e.canvas,b={},c=0;26>c;c++)b["Key"+"ABCDEFGHIJKLMNOPQRSTUVWXYZ"[c]]=c;for(c=0;10>c;c++)b["Digit"+c]=26+c;b.ArrowUp=
36;b.ArrowDown=37;b.ArrowLeft=38;b.ArrowRight=39;b.Space=40;b.Enter=41;b.Escape=42;b.Tab=43;b.Backspace=44;b.ShiftLeft=45;b.ShiftRight=46;b.ControlLeft=47;b.ControlRight=48;b.AltLeft=49;b.AltRight=50;for(c=1;12>=c;c++)b["F"+c]=50+c;b.Delete=63;b.Insert=64;b.Home=65;b.End=66;b.PageUp=67;b.PageDown=68;var d={Space:1,Tab:1,ArrowUp:1,ArrowDown:1,ArrowLeft:1,ArrowRight:1,F1:1,F2:1,F3:1,F4:1,F6:1,F7:1,F8:1,F9:1,F10:1},g=a.getBoundingClientRect();(new ResizeObserver(function(){g=a.getBoundingClientRect()})).observe(a);
e._ntKeyBuf=[];e._ntPtrBuf=[];e._ntWheelBuf=[];e._ntBlurred=!1;a.addEventListener("keydown",function(f){if(!f.repeat){var k=b[f.code];void 0!==k&&e._ntKeyBuf.push(k,1);d[f.code]&&f.preventDefault()}});a.addEventListener("keyup",function(f){f=b[f.code];void 0!==f&&e._ntKeyBuf.push(f,0)});a.addEventListener("blur",function(){e._ntBlurred=!0});a.addEventListener("pointerdown",function(f){a.focus();a.setPointerCapture(f.pointerId);e._ntPtrBuf.push(0,f.pointerId,f.clientX-g.left,f.clientY-g.top,f.pressure,
"touch"===f.pointerType?1:"pen"===f.pointerType?2:0,f.buttons);f.preventDefault()});a.addEventListener("pointermove",function(f){e._ntPtrBuf.push(1,f.pointerId,f.clientX-g.left,f.clientY-g.top,f.pressure,"touch"===f.pointerType?1:"pen"===f.pointerType?2:0,f.buttons)});a.addEventListener("pointerup",function(f){"mouse"===f.pointerType?e._ntPtrBuf.push(1,f.pointerId,f.clientX-g.left,f.clientY-g.top,f.pressure,0,f.buttons):e._ntPtrBuf.push(2,f.pointerId,0,0,0,0,0);f.preventDefault()});a.addEventListener("pointercancel",
function(f){e._ntPtrBuf.push(2,f.pointerId,0,0,0,0,0);f.preventDefault()});a.addEventListener("pointerleave",function(f){"mouse"===f.pointerType&&e._ntPtrBuf.push(2,f.pointerId,0,0,0,0,0)});a.addEventListener("wheel",function(f){var k=f.deltaX,m=f.deltaY;1===f.deltaMode?(k*=16,m*=16):2===f.deltaMode&&(k*=window.innerWidth,m*=window.innerHeight);e._ntWheelBuf.push(k,m);f.preventDefault()},{passive:!1});a.style.touchAction="none"},da:function(){var a=document.getElementById("spinner");a&&(a.style.display=
"none")},x:function(){return e.canvas.clientHeight},F:function(){return e.canvas.clientWidth},p:function(){return window.devicePixelRatio||1},o:function(a,b){e.canvas.width=a;e.canvas.height=b}},Y=function(){function a(c){Y=c.exports;A=Y.ea;ha();Aa=Y.ga;ja.unshift(Y.fa);G--;e.monitorRunDependencies?.(G);0==G&&(null!==H&&(clearInterval(H),H=null),I&&(c=I,I=null,c()));return Y}var b={a:Ia};G++;e.monitorRunDependencies?.(G);if(e.instantiateWasm)try{return e.instantiateWasm(b,a)}catch(c){return x(`Module.instantiateWasm callback failed with error: ${c}`),
!1}sa(b,function(c){a(c.instance)});return{}}(),Ja=e._main=(a,b)=>(Ja=e._main=Y.ha)(a,b);e._nt_input_web_on_key=(a,b)=>(e._nt_input_web_on_key=Y.ia)(a,b);e._nt_input_web_on_pointer_down=(a,b,c,d,g,f)=>(e._nt_input_web_on_pointer_down=Y.ja)(a,b,c,d,g,f);e._nt_input_web_on_pointer_move=(a,b,c,d,g,f)=>(e._nt_input_web_on_pointer_move=Y.ka)(a,b,c,d,g,f);e._nt_input_web_on_pointer_up=a=>(e._nt_input_web_on_pointer_up=Y.la)(a);e._nt_input_web_on_wheel=(a,b)=>(e._nt_input_web_on_wheel=Y.ma)(a,b);
e._nt_input_web_on_blur=()=>(e._nt_input_web_on_blur=Y.na)();e.___start_em_js=10612;e.___stop_em_js=14984;var Z;I=function Ka(){Z||La();Z||(I=Ka)};
function La(){function a(){if(!Z&&(Z=!0,e.calledRun=!0,!B)){K(ja);K(ka);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Ma){var b=Ja;try{var c=b(0,0);ta||(e.onExit?.(c),B=!0);h(c,new w(c))}catch(d){d instanceof w||"unwind"==d||h(1,d)}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)b=e.postRun.shift(),la.unshift(b);K(la)}}if(!(0<G)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)ma();K(ia);0<G||(e.setStatus?(e.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Ma=!0;e.noInitialRun&&(Ma=!1);La();
